apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader-reloader
spec:
  template:
    spec:
      containers:
        - name: reloader-reloader
          image: reg.ygnv.my.id/ghcr/stakater/reloader:v1.4.13
          args:
            - "--auto-reload-all=true"
            - "--reload-on-create=true"
            - "--log-format=json"
          resources:
            requests:
              memory: 32Mi
