apiVersion: apps/v1
kind: Deployment
metadata:
  name: bentopdf
  namespace: tools
  labels:
    app: bentopdf
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
    keel.sh/pollSchedule: "@every 6h"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: bentopdf
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bentopdf
    spec:
      containers:
      - name: bentopdf
        image: reg.ygnv.my.id/docker/bentopdf/bentopdf:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 64Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bentopdf
  namespace: tools
spec:
  selector:
    app: bentopdf
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bentopdf
  namespace: tools
  labels:
    app: bentopdf
spec:
  entryPoints:
  - http
  - https
  routes:
  - match: Host(`bentopdf.ygnv.my.id`)
    kind: Rule
    services:
    - name: bentopdf
      port: 8080
  tls:
    certResolver: cloudflare