apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawnix
  namespace: tools
  labels:
    app: drawnix
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: drawnix
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: drawnix
    spec:
      containers:
      - name: drawnix
        image: reg.ygnv.my.id/docker/pubuzhixing/drawnix:v0.2.0
        imagePullPolicy: IfNotPresent
        command: ["/busybox-httpd"]
        args: ["-f", "-v", "-p", "8000", "-c", "httpd.conf"]
        resources:
          requests:
            memory: 64Mi
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: drawnix
  namespace: tools
spec:
  selector:
    app: drawnix
  ports:
  - port: 8000
    targetPort: 8000

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: drawnix
  namespace: tools
spec:
  entryPoints:
  - http
  - https
  routes:
    - match: Host(`drawnix.ygnv.my.id`)
      kind: Rule
      services:
        - name: drawnix
          port: 8000
  tls:
    certResolver: cloudflare
