apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw
  namespace: tools
  labels:
    app: excalidraw
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: excalidraw
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: excalidraw
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: excalidraw
        image: reg.ygnv.my.id/docker/excalidraw/excalidraw:latest@sha256:d299ddcf67d815dd49f22fc7f22b41272afaafe3d0b73377f3b33d0d88a445c5
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 32Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw
  namespace: tools
spec:
  selector:
    app: excalidraw
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: excalidraw
  namespace: tools
  labels:
    app: excalidraw
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`excalidraw.ygnv.my.id`)
      kind: Rule
      services:
        - name: excalidraw
          port: 80
  tls:
    certResolver: cloudflare