apiVersion: v1
kind: ConfigMap
metadata:
  name: reactive-resume-env
  namespace: tools
data:
  PORT: 3000
  NODE_ENV: production

  # -- URLs --
  PUBLIC_URL: https://resume.ygnv.my.id
  STORAGE_URL: http://minio:9000/reactive

  # -- Printer (Chrome) --
  CHROME_URL: ws://chrome:3000

  # -- Emails --
  MAIL_FROM: noreply@localhost
  # SMTP_URL: smtp://user:pass@smtp:587 # Optional

  # -- Storage (Minio) --
  STORAGE_ENDPOINT: minio
  STORAGE_PORT: 9000
  STORAGE_REGION: ap-southeast-1 # Optional
  STORAGE_BUCKET: reactive
  STORAGE_USE_SSL: "false"
  STORAGE_SKIP_BUCKET_CHECK: "false"

  # -- Email (Optional) --
  # DISABLE_SIGNUPS: "false"
  # DISABLE_EMAIL_AUTH: "false"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
  namespace: tools
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      nodeSelector:
        kubernetes.io/hperf: "true"
      containers:
      - name: chrome
        image: reg.ygnv.my.id/ghcr/browserless/chromium:v2.33.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
        ports:
        - containerPort: 3000
        env:
        - name: HEALTH
          value: "true"
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: reactive-resume-cred
              key: CHROME_TOKEN
        - name: PROXY_PORT
          value: "3000"
        - name: PROXY_SSL
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: chrome
  namespace: tools
spec:
  selector:
    app: chrome
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive-resume
  namespace: tools
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: reactive-resume
  template:
    metadata:
      labels:
        app: reactive-resume
    spec:
      containers:
      - name: reactive-resume
        image: reg.ygnv.my.id/docker/amruthpillai/reactive-resume:v4.4.6
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
        ports:
          - containerPort: 3000
            name: http
        envFrom:
          - configMapRef:
              name: reactive-resume-env
          - secretRef:
              name: reactive-resume-cred
---
apiVersion: v1
kind: Service
metadata:
  name: reactive-resume
  namespace: tools
spec:
  selector:
    app: reactive-resume
  ports:
    - port: 3000
      targetPort: http
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: reactive-resume
  namespace: tools
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`resume.ygnv.my.id`)
      kind: Rule
      services:
        - name: reactive-resume
          port: 3000
  tls:
    certResolver: cloudflare