apiVersion: apps/v1
kind: Deployment
metadata:
  name: reubah
  namespace: tools
  labels:
    app: reubah
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll 
    keel.sh/match-tag: "true"
    keel.sh/pollSchedule: "@every 6h"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: reubah
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: reubah
    spec:
      containers:
      - name: reubah
        image: ghcr.io/dendianugerah/reubah:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 32Mi
        env:
        - name: PORT
          value: "8081"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: reubah
  namespace: tools
spec:
  selector:
    app: reubah
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: reubah
  namespace: tools
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`reubah.ygnv.my.id`)
      kind: Rule
      services:
        - name: reubah
          port: 8081
  tls:
    certResolver: cloudflare