apiVersion: apps/v1
kind: Deployment
metadata:
  name: vert
  namespace: tools
  labels:
    app: vert
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
    keel.sh/pollSchedule: "@every 6h"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vert
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vert
    spec:
      containers:
      - name: vert
        image: reg.ygnv.my.id/ghcr/vert-sh/vert:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 32Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vert
  namespace: tools
spec:
  selector:
    app: vert
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vert
  namespace: tools
  labels:
    app: vert
spec:
  entryPoints:
  - http
  - https
  routes:
  - match: Host(`vert.ygnv.my.id`)
    kind: Rule
    services:
    - name: vert
      port: 80
  tls:
    secretName: ygnv-wildcard-cert