apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  annotations:
    # Allow SealedSecrets to patch this secret
    sealedsecrets.bitnami.com/patch: "true"
    # Prevent SealedSecrets from taking ownership (ArgoCD manages this)
    sealedsecrets.bitnami.com/skip-set-owner-references: "true"
