apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-applicationset-controller
spec:
  template:
    spec:
      containers:
        - name: argocd-applicationset-controller
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      containers:
        - name: dex
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
spec:
  template:
    spec:
      containers:
        - name: argocd-notifications-controller
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
spec:
  template:
    spec:
      containers:
        - name: redis
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 16Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      initContainers:
        - name: copyutil
          imagePullPolicy: IfNotPresent
      containers:
        - name: argocd-repo-server
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      containers:
        - name: argocd-server
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 64Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  template:
    spec:
      containers:
        - name: argocd-application-controller
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 256Mi
