---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-cred
  namespace: cloudflare-operator-system
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgCeqc94E1Md7iFv2pNW4lPLRe5uQ8ITfvjfpSMaClaCZ9+5bFuLMHFnK34vWYMpWu6Yk59qAJl588PatYWPVy8jzIQljXfhXGREoR2RLLVA9DZMlyG1Bj+OqfZM0nHm9mRIIiPG4xQdijT59vBl2HZsKolwOz1yM+O58JMxxx94M2TXrOODlJG1EW1PkIPb2y+rIv4hrEeqQWE/9zXX+PyczLCR2Dd+j/tCljkZjGhhKKvCYq7vrFOVtC3hL0U1YoHE1PWsKUA2QFTmSnx1oFSpVy5oAfiE62bdxirxTgaEQVeRIAT3LbUO0xwlaWN7TaUNwlAjmb+d8lPSYNwUg/c5x5Go/TIeGjhPsgBic/qUGPkPKaL9gCCaH5eNX/KgHHAeKXBXVhXtLn4aezQx0Yqbb8ivNp8ph5LurRY0bno7d4/bD14Im8f/eW4c7LtQ+y6QOYRV5ijlGl/9+3OjC0+n4k5falcVJdnIfoqNDAgB03QkhNbO7p2Om3DeP6QR0rgm28I295CyFhx6GqRT71n3WS4bp0HybbM1CmTaxd2xw4v89aRUMkpc/UQzIjiiAGA2YBkQG+JLsHk4OrKU5VtlbdLYc+alTXLH1dWABcwhlG3GF0Kn8+bVEhGa9drR7a6GOZNnZeKjAIq7nMCKDC7A0BKLYJe2gCROO+1AY0+bisHDVcv/ruDi3Po+dRb4HvcZCnK4eBGqF0SlkmfKoSVEfmdLrCPwpcal+LqiPp7ItUc988vq/rNF
  template:
    metadata:
      name: cloudflare-cred
      namespace: cloudflare-operator-system
