apiVersion: networking.cfargotunnel.com/v1alpha2
kind: ClusterTunnel
metadata:
  name: homelab-tunnel-yoganova
spec:
  newTunnel:
    name: homelab-tunnel-yoganova
  size: 2
  cloudflare:
    domain: yoganova.my.id
    accountId: 97f22b27260f3bf4326b76a3fcb0fb9f
    email: yoga.november2000@gmail.com
    secret: cloudflare-cred
