apiVersion: networking.cfargotunnel.com/v1alpha2
kind: ClusterTunnel
metadata:
  name: homelab-tunnel-ygnv
spec:
  newTunnel:
    name: homelab-tunnel-ygnv
  # v1alpha2 uses deployPatch for replicas instead of 'size'
  # Inject Keel annotations to auto-update cloudflared image
  deployPatch: |
    {
      "metadata": {
        "annotations": {
          "keel.sh/policy": "force",
          "keel.sh/trigger": "poll",
          "keel.sh/match-tag": "true",
          "keel.sh/pollSchedule": "@every 6h"
        }
      },
      "spec": {
        "replicas": 1,
        "template": {
          "spec": {
            "containers": [
              {
                "resources": {
                  "requests": {
                    "cpu": "200m",
                    "memory": "32Mi"
                  }
                }
              }
            ]
          }
        }
      }
    }
  cloudflare:
    domain: ygnv.my.id
    accountId: 97f22b27260f3bf4326b76a3fcb0fb9f
    email: yoga.november2000@gmail.com
    secret: cloudflare-cred
