---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keel-cred
  namespace: keel
spec:
  encryptedData:
    BASIC_AUTH_PASSWORD: AgAkvLJdQ6QQJZXAb16ZGFRYNqoDroohSGV01MLDs4VskXaGGLug4q+gM+4EdV4rzhB9QLyqNvSZVhhFWfEa+/qO9AfJqmpO01BobpUoPtMgElR439FWR/PDsPcqp0w0qF/EttcrWtiY5Dr9VLCJ4mWjvoq/IqsHDi+25Le/KNgKCZ7ci90oNPBUpP6WNgPavaFfk8Aqjq+RWrj0OLg9cuz9R61F4/fxxt1EK5xJ6oKbwLNj6gVJZkiB9VAX6sCtYSAOllzadt71XeWe1c+9dknbwSLtcUzJbxWEPRP6n9TDggSKTfEKx07+Hf6roV+dEAnfrZsnnmoOIuPeRbuBg7tHshenZ3QBew511oEeOZVvq/3nZVXfOIxYz+8sSpiro5w+Yas2iKR5y872GZBrBDt7g4bq7jwMVuDz2fdqcqPmOmwd1jh8+23XuMjA3E18hME3rOZNR+ClraFtXz3bfTQ8IZNHUGOmUR2JluMz4OIv9GpkymdfU2A0gwkcdf2zhEVofYg+klLSE2wbLPC9Gy+D7xyoK7JDiEEhm7yk+IIcMpZ6pfn4UZcH/otc4dp7oKa2444ZoqUEGf6z5wh/ByPAquU+iglH5S029zCfDWUfw4tSj1+SRlntcsYr22Sw+zUYe89clfxFd4a8k9xm2fvps3HsXqjdsQ92CoKTS9Uim3niEaFxAAWxjZWUp5tnCN2iWK7K4QlO6Uw=
    BASIC_AUTH_USER: AgB1moklLj6BoGOuePudpC2Xw5iE+Td2HEE1jlxgDJpEHFci1PqK7ma4H2iITS1Pa7G+k08zPSWxCoWn0JnUie1e4HJh/EyjCWl87LKnALUX+lLqYBesCZWhTREOL1/SW1G/gqZIf/9ogs7rdBUhE63vRrNfcfgmqZC8RZd5Cmna3RQ7pwBu9LXYVb5qPU+fq0PZUrAHbdy10nH/CmkvXY2dbA0/Ihm08gSlwcr5qXKQ19XPG2LfmZKGuCUIxAy1T2vBrvkaD33aQNpIuC7nzjDUm/SqlnPqnuM4YH67Kj2yq+C0Nd5bPtNA9+JuRBkHVy630PQItCC90VBVMo6KlsSTl04fhcP36s+7r+NJSdw29el6nqI+4+ShxBThJmsRpxhGcPtTV+V6G3UxWOXU8CgIWmQFjDQ6hL7i5AsNFLmBDl1Ul6O+PkLpIi3Mf2bS6RgYyZtx0Impr5/NExIW7bldoslpfZYGdbJh5FHMDpqtG4sW12M7Y6I1Uu0C0auzh/8Q33EeNsN56yVkXhKw+4KFGSKAJ1EGW63Lv8+QkhNo6G8LFssFinG+S9hEgpl8hMJlJt/qcZrLxHXrLE34ro3ay3sEU5wND1QhE7SWsgDx0eXfwqq7QQZ34zhYMKMtYu5PYzSKahd2tqQJJMdYH8+rcCkTcPV8qzvIpLu7jLFVLiZRjsSUtm/zzeTqE/UFePf75wy5
  template:
    metadata:
      creationTimestamp: null
      name: keel-cred
      namespace: keel
    type: Opaque
