apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-keel-bridge
  namespace: keel
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: discord-keel-bridge
  template:
    metadata:
      labels:
        app: discord-keel-bridge
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: discord-keel-bridge
        image: gabisonfire/discord-keel-bridge:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: 64Mi
        env:
        - name: DISCORD_BRIDGE_URL
          valueFrom:
            secretKeyRef:
              name: keel-cred
              key: DISCORD_BRIDGE_URL
        - name: DISCORD_BRIDGE_PORT
          value: "5000"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: discord-keel-bridge
  namespace: keel
spec:
  selector:
    app: discord-keel-bridge
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
