---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: services
  labels:
    app: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
  labels:
    app: external-dns
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  labels:
    app: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: services
  labels:
    app: external-dns
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.20.0
          imagePullPolicy: IfNotPresent
          args:
            - --source=ingress
            - --source=service
            - --publish-internal-services
            # Manage root domain ygnv.my.id (only if explicitly annotated)
            # Manage all subdomains for yoganova.my.id
            - --domain-filter=ygnv.my.id
            - --domain-filter=yoganova.my.id
            - --default-targets=9141b1d3-89ab-4302-a7eb-7eede71828fd.cfargotunnel.com
            - --provider=cloudflare
            - --cloudflare-dns-records-per-page=100
            - --cloudflare-record-comment="provisioned by external-dns"
            - --log-format=json
            - --log-level=info
            - --interval=2m
          env:
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: external-dns-cred
                  key: CF_API_TOKEN
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
