---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-sa
  namespace: tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-role
  namespace: tools
rules:
- apiGroups: ["apps"]
  resources: ["deployments/scale"]            # grant access to the scale subresource
  verbs: ["get", "patch"]                     # need get to read .spec.replicas and patch to change it :contentReference[oaicite:2]{index=2}
- apiGroups: [""]                             # core API
  resources: ["pods"]
  verbs: ["list", "get", "watch"]             # to wait for Pods to terminate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-rolebinding
  namespace: tools
subjects:
- kind: ServiceAccount
  name: backup-sa
  namespace: tools
roleRef:
  kind: Role
  name: backup-role
  apiGroup: rbac.authorization.k8s.io