{
 "title": "Promtail Monitoring - Metrics and Logs",
 "description": "Monitor Promtail metrics and logs",
 "tags": [ "promtail" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource Loki", "query": "loki" },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {}
   },
   { "name": "job", "label": "Job", "query": "journald_logs, system_logs" },
   { "name": "filter", "label": "LogQL Filter" }
  ]
 },
 "panels": [
  { "title": "Promtail - Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DEBUG Log Lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({job=~\"$job\", instance=~\"$instance\"} | logfmt | level = `debug` | __error__=`` [$__range]))"
    }
   ]
  },
  {
   "title": "INFO Log Lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({job=~\"$job\", instance=~\"$instance\"} | logfmt | level = `info` | __error__=`` [$__range]))"
    }
   ]
  },
  {
   "title": "WARN Log Lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({job=~\"$job\", instance=~\"$instance\"} | logfmt | level = `warn` | __error__=`` [$__range]))"
    }
   ]
  },
  {
   "title": "ERROR Log Lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({job=~\"$job\", instance=~\"$instance\"} | logfmt | level=\"error\" | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Promtail Log Lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\"} | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Promtail Log in bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({job=~\"$job\", instance=~\"$instance\"} | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Promtail Recent Logs",
   "type": "logs",
   "description": "Use LogQL Filter to filter information.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{job=~\"$job\", instance=~\"$instance\"} | logfmt | level = `debug` |= `$filter` | line_format `➡️ 🔵 {{regexReplaceAll \"level=debug|ts=[^\\\\s]+\\\\s\" __line__ \"$1\" | trim  }}`"
    },
    {
     "expr": "{job=~\"$job\", instance=~\"$instance\"} | logfmt | level=\"info\" |= \"$filter\" | line_format `➡️ 🟢 {{regexReplaceAll \"level=info|ts=[^\\\\s]+\\\\s\" __line__ \"$1\" | trim }}`"
    },
    {
     "expr": "{job=~\"$job\", instance=~\"$instance\"} | logfmt | level=\"warn\" |= \"$filter\" | line_format `➡️ 🟡 {{regexReplaceAll \"level=warn|ts=[^\\\\s]+\\\\s\" __line__ \"$1\" | trim  }}`"
    },
    {
     "expr": "{job=~\"$job\", instance=~\"$instance\"} | logfmt | level=\"error\" |= \"$filter\" | line_format `➡️ 🔴 {{regexReplaceAll \"level=error|ts=[^\\\\s]+\\\\s\" __line__ \"$1\" | trim  }}`"
    }
   ]
  },
  {
   "title": "Error Requests and Logs Count - Overtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({job=~\"$job\", instance=~\"$instance\"} | logfmt | level = `warn` | __error__=`` [$__auto]))",
     "legendFormat": "Warning Logs Lines"
    },
    {
     "expr": "sum by (level) (count_over_time({job=~\"$job\", instance=~\"$instance\"} | logfmt | level=\"error\" | __error__=\"\"[$__auto]))",
     "legendFormat": "Error Logs Lines"
    }
   ]
  },
  {
   "title": "Promtail Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Bytes - Overtime",
     "type": "timeseries",
     "description": "Number of bytes read. - Overtime",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(promtail_read_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Read Bytes - Details",
     "type": "table",
     "gridPos": { "h": 12, "w": 10, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "promtail_read_bytes_total{job=~\"$job\", instance=~\"$instance.*\"} "
      },
      {
       "expr": "rate(promtail_read_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])"
      },
      {
       "expr": "rate(promtail_read_lines_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])"
      },
      {
       "expr": "increase(promtail_read_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[24h])"
      }
     ]
    },
    {
     "title": "Encoded and Send Bytes - Overtime",
     "type": "timeseries",
     "description": "- Encoded: Number of bytes encoded and ready to send.\n- Send: Number of bytes sent. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(promtail_encoded_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])",
       "legendFormat": "Encoded Bytes"
      },
      {
       "expr": "rate(promtail_sent_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])",
       "legendFormat": "Send Bytes"
      }
     ]
    },
    {
     "title": "Encoded and Send - Details",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(promtail_sent_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])"
      },
      {
       "expr": "increase(promtail_sent_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[24h])"
      },
      {
       "expr": "rate(promtail_encoded_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])"
      },
      {
       "expr": "increase(promtail_encoded_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[24h])"
      }
     ]
    },
    {
     "title": "Dropped Bytes - Overtime",
     "type": "timeseries",
     "description": "- Dropped Bytes: Number of bytes dropped because failed to be sent to the ingester after all retries.\n- Dropped Entries: Number of log entries dropped because failed to be sent to the ingester after all retries.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(promtail_dropped_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])",
       "legendFormat": "Dropped Bytes - {{reason}}"
      },
      {
       "expr": "rate(promtail_dropped_entries_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])",
       "legendFormat": "Dropped Entries - {{reason}}"
      }
     ]
    },
    {
     "title": "Request Latency - 99th Percentile Latency",
     "type": "timeseries",
     "description": "99th percentile latency",
     "gridPos": { "h": 8, "w": 10, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(promtail_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance.*\"}[5m])) by (le))",
       "legendFormat": "Request Latency"
      }
     ]
    }
   ]
  }
 ]
}