{
 "title": "Traefik On K8s Via Loki",
 "description": "Loki on k8s using JSON Traefik access logs.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "loki_datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"left dashboard-header\">\n   <img src=\"https://marketplace-assets.digitalocean.com/logos/loki-logo.svg\" style=\"height:29px;\"/>\n  <span>Traefik Dashboard</span>\n</div>"
   }
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({kubernetes_container_name=~\"traefik\"} |= \"RequestProtocol\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (log_processed_OriginStatus) (count_over_time({kubernetes_container_name=~\"traefik\"}|= \"RequestProtocol\" | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{log_processed_OriginStatus}}"
    }
   ]
  },
  {
   "title": "% of  4/5xx ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum(rate({kubernetes_container_name=~\"traefik\"} |~ \"RequestProtocol\" | json | log_processed_OriginStatus >= 400 |__error__=\"\"[$__interval])) / (sum(rate({kubernetes_container_name=~\"traefik\"} |~ \"RequestProtocol\" | json | __error__=\"\"[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": " 4/5xx  Services",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (log_processed_OriginStatus,log_processed_ServiceName) (count_over_time({kubernetes_container_name=~\"traefik\"} |~ \"RequestProtocol\" | json | log_processed_OriginStatus >= 400 |__error__=\"\"[$__interval]))",
     "legendFormat": " {{log_processed_ServiceName}} / {{log_processed_OriginStatus}} "
    }
   ]
  },
  {
   "title": "Users right now",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (log_processed_ClientHost) (count_over_time({kubernetes_container_name=~\"traefik\"}|= \"RequestProtocol\" | json |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time({kubernetes_container_name=~\"traefik\"}|= \"RequestProtocol\" | json | log_processed_OriginStatus=200 | unwrap log_processed_DownstreamContentSize |  __error__=\"\" [$__interval])",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Requests Route",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (log_processed_RouterName) (count_over_time({kubernetes_container_name=~\"traefik\"}|= \"RequestProtocol\" | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "{{log_processed_RouterName}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "{kubernetes_container_name=~\"traefik\"} |= \"RequestProtocol\"| json  | line_format \"Status:{{.log_processed_OriginStatus}} Client From {{.log_processed_ClientAddr}} {{.log_processed_RequestMethod}} {{.log_processed_RequestAddr}}{{.log_processed_RequestPath}} Route To {{.log_processed_ServiceAddr}}\""
    }
   ]
  },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{kubernetes_container_name=~\"traefik\"} |= \"RequestProtocol\"| json | unwrap log_processed_Duration |  __error__=\"\"  [$__interval]) by (log_processed_ServiceName)",
     "legendFormat": " {{ log_processed_ServiceName }}"
    }
   ]
  },
  {
   "title": "Max Age of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max by (log_processed_ServiceName) (max_over_time({kubernetes_container_name=~\"traefik\"} |= \"RequestProtocol\" |json | unwrap log_processed_Duration |  __error__=\"\"  [$__interval]))",
     "legendFormat": "{{ log_processed_ServiceName}}"
    }
   ]
  },
  {
   "title": "Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (log_processed_ServiceName) (sum_over_time({kubernetes_container_name=~\"traefik\"} |= \"RequestProtocol\" |json | unwrap log_processed_RequestContentSize |  __error__=\"\"  [$__interval]))",
     "legendFormat": "{{ log_processed_ServiceName}}"
    }
   ]
  }
 ]
}