apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "events"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [INPUT]
        name              kubernetes_events
        tag               k8s_events

    # [FILTER]
    #     Name             kubernetes
    #     Match            k8s_events
    #     Kube_URL         https://kubernetes.default.svc:443
    #     Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    #     Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
    #     Labels           On
    #     Annotations      On

    [FILTER]
        Name             modify
        Match            k8s_events
        labels           On
        Annotations      On
        Rename           kubernetes.host       hostname

    [OUTPUT]
        Name            loki
        Match           *
        Host            loki.monitoring.svc.cluster.local
        Port            3100
        Labels          job=fluent-bit
        
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:4.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: 32Mi
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
      volumes:
      - name: config
        configMap:
          name: fluent-bit-config