apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "events", "nodes", "nodes/proxy"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-logs-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush                     1
        Log_Level                 info
        Parsers_File              parsers.conf
        storage.path              /var/log/flb-storage/
        storage.sync              normal
        storage.checksum          on
        storage.backlog.mem_limit 16M

    [INPUT]
        Name                      tail
        Tag                       kube.*
        storage.type              filesystem
        Path                      /var/log/containers/*.log
        multiline.parser          docker, cri
        DB                        /var/log/flb_kube.db
        Mem_Buf_Limit             32MB
        Skip_Long_Lines           On

    [FILTER]
        Name                      kubernetes
        Match                     kube.*
        Kube_URL                  https://kubernetes.default.svc:443
        Kube_CA_File              /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File           /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix           kube.var.log.containers.
        Merge_Log                 On
        Merge_Log_Key             log_processed
        Merge_Log_Trim            On
        Keep_Log                  off
        labels                    On
        Annotations               Off
        Use_Tag_For_Meta          On

    [OUTPUT]
        Name                      loki
        Match                     kube.*
        Host                      loki.monitoring
        Port                      3100
        Labels                    source=fluent_bit,job=kube_logs
        Label_Keys                $kubernetes['namespace_name'],$kubernetes['pod_name'],$kubernetes['container_name']
        auto_kubernetes_labels    On

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-events-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush                     1
        Log_Level                 info
        Parsers_File              parsers.conf
        storage.path              /var/log/flb-storage/
        storage.sync              normal
        storage.checksum          on
        storage.backlog.mem_limit 16M

    [INPUT]
        Name                      kubernetes_events
        Tag                       k8s_events
        storage.type              filesystem
        DB                        /var/log/flb_kube_events.db
        Mem_Buf_Limit             32MB

    [FILTER]
        Name                      modify
        Match                     k8s_events
        Rename                    kubernetes.host       hostname

    [OUTPUT]
        Name                      loki
        Match                     k8s_events
        Host                      loki.monitoring
        Port                      3100
        Labels                    source=fluent_bit,job=kube_events
        auto_kubernetes_labels    On
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-logs
  namespace: monitoring
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: fluent-logs
  template:
    metadata:
      labels:
        app: fluent-logs
    spec:
      serviceAccountName: fluent-bit
      containers:
        - name: fluent-logs
          image: reg.ygnv.my.id/docker/fluent/fluent-bit:4.2.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 32Mi
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: config
          configMap:
            name: fluent-logs-config
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-events
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: fluent-events
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fluent-events
    spec:
      serviceAccountName: fluent-bit
      containers:
        - name: fluent-events
          image: reg.ygnv.my.id/docker/fluent/fluent-bit:4.2.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 32Mi
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: config
          configMap:
            name: fluent-events-config
        - name: varlog
          hostPath:
            path: /mnt/cephfs/docker/monitoring/fluent-events
            type: Directory
