apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-env
  namespace: monitoring
data:
  DOCKER_INFLUXDB_INIT_MODE: "setup"
  DOCKER_INFLUXDB_INIT_ORG: "myorg"
  DOCKER_INFLUXDB_INIT_BUCKET: "proxmox"
  DOCKER_INFLUXDB_INIT_RETENTION: "30d"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    app: influxdb

spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:2.7.11
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
        envFrom:
        - secretRef:
            name: influxdb-cred
        - configMapRef:
            name: influxdb-env
        volumeMounts:
        - name: influxdb-data
          mountPath: /var/lib/influxdb2
        - name: influxdb-config
          mountPath: /etc/influxdb2
      volumes:
      - name: influxdb-data
        hostPath:
          path: /mnt/cephfs/docker/monitoring/influxdb
          type: Directory
      - name: influxdb-config
        hostPath:
          path: /mnt/cephfs/docker/monitoring/influxdb_config
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    app: influxdb
spec:
  type: LoadBalancer
  externalIPs:
    - 10.1.1.10
  selector:
    app: influxdb
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086
---

