apiVersion: v1
kind: ConfigMap
metadata:
  name: mktxp-config
  namespace: monitoring
data:
  mktxp.conf: |
    ## Copyright (c) 2020 Arseniy Kuznetsov
    ##
    ## This program is free software; you can redistribute it and/or
    ## modify it under the terms of the GNU General Public License
    ## as published by the Free Software Foundation; either version 2
    ## of the License, or (at your option) any later version.
    ##
    ## This program is distributed in the hope that it will be useful,
    ## but WITHOUT ANY WARRANTY; without even the implied warranty of
    ## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ## GNU General Public License for more details.


    [RB750R2]
        # for specific configuration on the router level, change here the defaults values from below
        hostname = ${RB750R2}

    [SXT5HPnD]
        hostname = ${SXT5HPnD}

    [default]
        # this affects configuration of all routers, unless overloaded on their specific levels

        enabled = True          # turns metrics collection for this RouterOS device on / off
        hostname = localhost    # RouterOS IP address
        port = 8728             # RouterOS IP Port
        
        username = ${USERNAME}     # RouterOS user, needs to have 'read' and 'api' permissions
        password = ${PASSWORD}     
        
        use_ssl = False                 # enables connection via API-SSL servis
        no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
        ssl_certificate_verify = False  # turns SSL certificate verification on / off   
        plaintext_login = True          # for legacy RouterOS versions below 6.43 use False

        installed_packages = True       # Installed packages
        dhcp = True                     # DHCP general metrics
        dhcp_lease = True               # DHCP lease metrics

        connections = True              # IP connections metrics
        connection_stats = False        # Open IP connections metrics 

        interface = True                # Interfaces traffic metrics
        
        route = True                    # IPv4 Routes metrics
        pool = True                     # IPv4 Pool metrics
        firewall = True                 # IPv4 Firewall rules traffic metrics
        neighbor = True                 # IPv4 Reachable Neighbors

        ipv6_route = False              # IPv6 Routes metrics    
        ipv6_pool = False               # IPv6 Pool metrics
        ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
        ipv6_neighbor = False           # IPv6 Reachable Neighbors

        poe = True                      # POE metrics
        monitor = True                  # Interface monitor metrics
        netwatch = True                 # Netwatch metrics
        public_ip = True                # Public IP metrics
        wireless = True                 # WLAN general metrics
        wireless_clients = True         # WLAN clients metrics
        capsman = True                  # CAPsMAN general metrics
        capsman_clients = True          # CAPsMAN clients metrics

        lte = False                     # LTE signal and status metrics
        ipsec = False                   # IPSec active peer metrics

        kid_control_assigned = False    # Allow Kid Control metrics for connected devices with assigned users
        kid_control_dynamic = False     # Allow Kid Control metrics for all connected devices, including those without assigned user

        user = True                     # Active Users metrics
        queue = True                    # Queues metrics

        bgp = False                     # BGP sessions metrics
        
        remote_dhcp_entry = None        # An MKTXP entry to provide for remote DHCP info / resolution
        remote_capsman_entry = None     # An MKTXP entry to provide for remote capsman info 

        use_comments_over_names = True  # when available, forces using comments over the interfaces names
        check_for_updates = False       # check for available ROS updates

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mktxp
  namespace: monitoring
  labels:
    app: mktxp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mktxp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mktxp
    spec:
      containers:
      - name: mktxp
        image: reg.ygnv.my.id/ghcr/akpw/mktxp:1.2.12
        imagePullPolicy: Always
        resources:
          requests:
            memory: 64Mi
        ports: 
        - containerPort: 49090
        securityContext:
          runAsUser: 0  # run as root, per original config
        volumeMounts:
        - name: mktxp-volume
          mountPath: /root/mktxp/
      initContainers:
        - name: config-processor
          image: reg.ygnv.my.id/docker/alpine:3.22.1
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - apk add --no-cache gettext;
              envsubst < /config-template/mktxp.conf > /mktxp-volume/mktxp.conf;
          volumeMounts:
            - name: config-template
              mountPath: /config-template
            - name: mktxp-volume
              mountPath: /mktxp-volume
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: mktxp-cred
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mktxp-cred
                  key: password
            - name: RB750R2
              valueFrom:
                secretKeyRef:
                  name: mktxp-cred
                  key: rb750r2
            - name: SXT5HPnD
              valueFrom:
                secretKeyRef:
                  name: mktxp-cred
                  key: sxt5hpd
      volumes:
        - name: mktxp-volume
          emptyDir: {}
        - name: config-template
          configMap:
            name: mktxp-config
---
apiVersion: v1
kind: Service
metadata:
  name: mktxp
  namespace: monitoring
  labels:
    app: mktxp
spec:
  type: ClusterIP
  selector:
    app: mktxp
  ports:
  - protocol: TCP
    port: 49090
    targetPort: 49090