apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
# 🌐 Nginx configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: peekaping-nginx
  namespace: monitoring
data:
  nginx.conf: |
    events {}
    http {
      upstream api {
        server peekaping-api:8034;
      }
      upstream web {
        server peekaping-web:80;
      }

      server {
        listen 80;

        location /api/ {
          proxy_pass http://api;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }

        location /socket.io/ {
          proxy_pass http://api;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }

        location / {
          proxy_pass http://web;
        }
      }
    }
---
# 🗃️ MongoDB
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peekaping-mongo
  namespace: monitoring
spec:
  serviceName: peekaping-mongo
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: peekaping-mongo
  template:
    metadata:
      labels:
        app: peekaping-mongo
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: mongo
          image: reg.ygnv.my.id/docker/mongo:8.2.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 256Mi
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: peekaping-cred
                  key: DB_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: peekaping-cred
                  key: DB_PASS
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: peekaping-cred
                  key: DB_NAME
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          readinessProbe:
            exec:
              command: ["mongosh", "--eval", "db.runCommand('ping').ok"]
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: mongo-data
          hostPath:
            path: /mnt/cephfs/docker/monitoring/peekaping/mongo
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: peekaping-mongo
  namespace: monitoring
spec:
  selector:
    app: peekaping-mongo
  ports:
    - port: 27017
      targetPort: 27017
---
# 🔁 Valkey (Redis-compatible)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peekaping-valkey
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: peekaping-valkey
  template:
    metadata:
      labels:
        app: peekaping-valkey
    spec:
      containers:
        - name: valkey
          image: reg.ygnv.my.id/docker/valkey/valkey:9.0-alpine
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 16Mi
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["valkey-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 30
          volumeMounts:
            - name: valkey-data
              mountPath: /data
      volumes:
        - name: valkey-data
          hostPath:
            path: /mnt/cephfs/docker/monitoring/peekaping/valkey
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: peekaping-valkey
  namespace: monitoring
spec:
  selector:
    app: peekaping-valkey
  ports:
    - port: 6379
      targetPort: 6379

---
# ⚙️ API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peekaping-api
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: peekaping-api
  template:
    metadata:
      labels:
        app: peekaping-api
    spec:
      containers:
        - name: api
          image: reg.ygnv.my.id/docker/0xfurai/peekaping-api:0.0.44
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 64Mi
          envFrom:
            - secretRef:
                name: peekaping-cred
          ports:
            - containerPort: 8034
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8034
            initialDelaySeconds: 15
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: peekaping-api
  namespace: monitoring
spec:
  selector:
    app: peekaping-api
  ports:
    - port: 8034
      targetPort: 8034
---
# 🧮 Producer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peekaping-producer
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: peekaping-producer
  template:
    metadata:
      labels:
        app: peekaping-producer
    spec:
      containers:
        - name: producer
          image: reg.ygnv.my.id/docker/0xfurai/peekaping-producer:0.0.44
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 32Mi
          envFrom:
            - secretRef:
                name: peekaping-cred
---
# ⚙️ Worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peekaping-worker
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: peekaping-worker
  template:
    metadata:
      labels:
        app: peekaping-worker
    spec:
      containers:
        - name: worker
          image: reg.ygnv.my.id/docker/0xfurai/peekaping-worker:0.0.44
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 32Mi
          envFrom:
            - secretRef:
                name: peekaping-cred
---
# 📥 Ingester
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peekaping-ingester
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: peekaping-ingester
  template:
    metadata:
      labels:
        app: peekaping-ingester
    spec:
      containers:
        - name: ingester
          image: reg.ygnv.my.id/docker/0xfurai/peekaping-ingester:0.0.44
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 32Mi
          envFrom:
            - secretRef:
                name: peekaping-cred
---
# 🌐 Web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peekaping-web
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: peekaping-web
  template:
    metadata:
      labels:
        app: peekaping-web
    spec:
      containers:
        - name: web
          image: reg.ygnv.my.id/docker/0xfurai/peekaping-web:0.0.44
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 32Mi
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: peekaping-web
  namespace: monitoring
spec:
  selector:
    app: peekaping-web
  ports:
    - port: 80
      targetPort: 80
---
# 🚪 Gateway (Nginx)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peekaping-gateway
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: peekaping-gateway
  template:
    metadata:
      labels:
        app: peekaping-gateway
    spec:
      containers:
        - name: nginx
          image: reg.ygnv.my.id/docker/nginx:1.29.3-alpine
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 16Mi
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: peekaping-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: peekaping-gateway
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: peekaping-gateway
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

---
# 📶 IngressRoute (Traefik
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: peekaping-gateway
  namespace: monitoring
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`peekaping.ygnv.my.id`)
      kind: Rule
      services:
        - name: peekaping-gateway
          port: 80
  tls:
    certResolver: cloudflare
