apiVersion: apps/v1
kind: Deployment
metadata:
  name: pve-exporter
  namespace: monitoring
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pve-exporter
  template:
    metadata:
      labels:
        app: pve-exporter
    spec:
      containers:
      - name: exporter
        image: reg.ygnv.my.id/docker/prompve/prometheus-pve-exporter
        imagePullPolicy: Always
        resources:
          requests:
            memory: 32Mi
        envFrom:
          - secretRef:
              name: pve-exporter-cred
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pve-exporter
  namespace: monitoring
spec:
  selector:
    app: pve-exporter
  ports:
    - protocol: TCP
      port: 9221
      targetPort: 9221