# Bazarr Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media
  labels:
    app: bazarr
spec:
  replicas: 1

  selector:
    matchLabels:
      app: bazarr
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          image: reg.ygnv.my.id/docker/linuxserver/bazarr:1.5.5
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 256Mi
          ports:
            - containerPort: 6767
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Jakarta"
          volumeMounts:
            - name: bazarr-config
              mountPath: /config
            - name: bazarr-movies
              mountPath: /movies
            - name: bazarr-tv
              mountPath: /tv
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: media-bazarr-pvc
        - name: bazarr-movies
          hostPath:
            path: /mnt/cephfs/data/Videos/Movies
            type: Directory
        - name: bazarr-tv
          hostPath:
            path: /mnt/cephfs/data/Videos/TV
            type: Directory
---
# Bazarr Service
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: media
  labels:
    app: bazarr
spec:
  selector:
    app: bazarr
  ports:
    - protocol: TCP
      port: 6767
      targetPort: 6767
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr
  namespace: media
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`bazarr.ygnv.my.id`)
      kind: Rule
      services:
        - name: bazarr
          port: 6767
  tls: {}
