# Transmission Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: media
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: lscr.io/linuxserver/transmission:4.0.6
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
          name: http
        - containerPort: 51413
          name: torrent-tcp
          protocol: TCP
        - containerPort: 51413
          name: torrent-udp
          protocol: UDP
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: USER
          valueFrom:
            secretKeyRef:
              name: download-cred
              key: user
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: download-cred
              key: pass
        - name: DOCKER_MODS
          value: "linuxserver/mods:transmission-floodui"
        volumeMounts:
        - name: transmission-config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        - name: torrent-watch
          mountPath: /watch
      volumes:
      - name: transmission-config
        hostPath:
          path: /mnt/cephfs/docker/download/transmission
          type: Directory
      - name: downloads
        hostPath:
          path: /mnt/Data/downloads
          type: Directory
      - name: torrent-watch
        hostPath:
          path: /mnt/Data/downloads/torrent
          type: Directory
---
# Transmission Service
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: media
  labels:
    app: transmission
spec:
  type: LoadBalancer
  externalIPs:
    - 10.1.1.250
  selector:
    app: transmission
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
  - name: torrent-tcp
    protocol: TCP
    port: 51413
    targetPort: 51413
  - name: torrent-udp
    protocol: UDP
    port: 51413
    targetPort: 51413
---
# Aria2 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aria2
  namespace: media
  labels:
    app: aria2
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
    keel.sh/pollSchedule: "@every 6h"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aria2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aria2
    spec:
      containers:
      - name: aria2
        image: p3terx/aria2-pro:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6800
          name: rpc
        - containerPort: 6888
          name: listen-tcp
          protocol: TCP
        - containerPort: 6888
          name: listen-udp
          protocol: UDP
        env:
        - name: PUID
          value: "65534"
        - name: PGID
          value: "65534"
        - name: UMASK_SET
          value: "022"
        - name: RPC_SECRET
          valueFrom:
            secretKeyRef:
              name: download-cred
              key: pass
        - name: RPC_PORT
          value: "6800"
        - name: LISTEN_PORT
          value: "6888"
        - name: DISK_CACHE
          value: "128M"
        - name: IPV6_MODE
          value: "false"
        - name: UPDATE_TRACKERS
          value: "true"
        - name: CUSTOM_TRACKER_URL
          value: ""
        - name: TZ
          value: "Asia/Jakarta"
        volumeMounts:
        - name: aria2-config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: aria2-config
        hostPath:
          path: /mnt/cephfs/docker/download/aria2
          type: Directory
      - name: downloads
        hostPath:
          path: /mnt/Data/downloads
          type: Directory
---
# Aria2 Service
apiVersion: v1
kind: Service
metadata:
  name: aria2
  namespace: media
  labels:
    app: aria2
spec:
  type: LoadBalancer
  externalIPs:
    - 10.1.1.250
  selector:
    app: aria2
  ports:
  - name: rpc
    protocol: TCP
    port: 6800
    targetPort: 6800
  - name: listen-tcp
    protocol: TCP
    port: 6888
    targetPort: 6888
  - name: listen-udp
    protocol: UDP
    port: 6888
    targetPort: 6888
