# Maintainerr Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintainerr
  namespace: media
  labels:
    app: maintainerr
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: maintainerr
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: maintainerr
    spec:
      containers:
        - name: maintainerr
          image: reg.ygnv.my.id/ghcr/maintainerr/maintainerr:2.26.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 128Mi
          ports:
            - containerPort: 6246
          env:
            - name: TZ
              value: "Asia/Jakarta"
          volumeMounts:
            - name: maintainerr-data
              mountPath: /opt/data
      volumes:
        - name: maintainerr-data
          persistentVolumeClaim:
            claimName: media-maintainerr-pvc
---
# Maintainerr Service
apiVersion: v1
kind: Service
metadata:
  name: maintainerr
  namespace: media
  labels:
    app: maintainerr
spec:
  selector:
    app: maintainerr
  ports:
    - protocol: TCP
      port: 6246
      targetPort: 6246
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: maintainerr
  namespace: media
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`maintainerr.ygnv.my.id`)
      kind: Rule
      services:
        - name: maintainerr
          port: 6246
  tls: {}
