# Overseerr Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: media
  labels:
    app: overseerr
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: overseerr
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
        - name: overseerr
          image: reg.ygnv.my.id/docker/sctx/overseerr:1.34.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 256Mi
          ports:
            - containerPort: 5055
          env:
            - name: LOG_LEVEL
              value: info
            - name: TZ
              value: "Asia/Jakarta"
          volumeMounts:
            - name: overseerr-config
              mountPath: /app/config
      volumes:
        - name: overseerr-config
          persistentVolumeClaim:
            claimName: media-overseerr-pvc
---
# Overseerr Service
apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: media
  labels:
    app: overseerr
spec:
  selector:
    app: overseerr
  ports:
    - protocol: TCP
      port: 5055
      targetPort: 5055
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: overseerr
  namespace: media
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`overseerr.ygnv.my.id`)
      kind: Rule
      services:
        - name: overseerr
          port: 5055
  tls: {}
