apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
  labels:
    app: plex
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: plex
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: plex
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube-2
      # securityContext:
      #   supplementalGroups:
      #     - 44   # GID for video group
      #     - 109  # GID for render group
      containers:
        - name: plex
          image: reg.ygnv.my.id/docker/linuxserver/plex:1.42.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 256Mi
          ports:
            - containerPort: 32400
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: VERSION
              value: "docker"
          volumeMounts:
            - name: dev-dri
              mountPath: /dev/dri
            - name: plex-config
              mountPath: /config
            - name: plex-tv
              mountPath: /tv
            - name: plex-movies
              mountPath: /movies
          securityContext:
            privileged: false
      volumes:
        - name: dev-dri
          hostPath:
            path: /dev/dri
            type: Directory
        - name: plex-config
          persistentVolumeClaim:
            claimName: media-plex-pvc
        - name: plex-tv
          hostPath:
            path: /mnt/cephfs/data/Videos/TV
            type: Directory
        - name: plex-movies
          hostPath:
            path: /mnt/cephfs/data/Videos/Movies
            type: Directory
---
# Plex Service
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
  labels:
    app: plex
  annotations:
    metallb.io/address-pool: "main-pool"
    metallb.io/allow-shared-ip: "media"
spec:
  selector:
    app: plex
  type: LoadBalancer
  loadBalancerIP: 10.1.1.53
  externalIPs:
    - 10.1.1.11
  ports:
    - protocol: TCP
      port: 32400
      targetPort: 32400
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex
  namespace: media
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`plex.ygnv.my.id`)
      kind: Rule
      services:
        - name: plex
          port: 32400
  tls: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
  labels:
    app: jellyfin
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube-2
      # securityContext:
      #   supplementalGroups:
      #     - 44   # GID for video group
      #     - 109  # GID for render group
      containers:
        - name: jellyfin
          image: reg.ygnv.my.id/ghcr/jellyfin/jellyfin:10.11.5
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 256Mi
          ports:
            - containerPort: 8096
          env:
            - name: TZ
              value: "Asia/Jakarta"
          volumeMounts:
            - name: dev-dri
              mountPath: /dev/dri
            - name: jellyfin-config
              mountPath: /config
            - name: jellyfin-cache
              mountPath: /cache
            - name: jellyfin-tvshows
              mountPath: /data/tvshows
            - name: jellyfin-movies
              mountPath: /data/movies
          securityContext:
            privileged: true
      volumes:
        - name: dev-dri
          hostPath:
            path: /dev/dri
            type: Directory
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: media-jellyfin-config-pvc
        - name: jellyfin-cache
          persistentVolumeClaim:
            claimName: media-jellyfin-cache-pvc
        - name: jellyfin-tvshows
          hostPath:
            path: /mnt/cephfs/data/Videos/TV
            type: Directory
        - name: jellyfin-movies
          hostPath:
            path: /mnt/cephfs/data/Videos/Movies
            type: Directory
---
# Jellyfin Service
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
  labels:
    app: jellyfin
  annotations:
    metallb.io/address-pool: "main-pool"
    metallb.io/allow-shared-ip: "media"
spec:
  selector:
    app: jellyfin
  type: LoadBalancer
  loadBalancerIP: 10.1.1.53
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: media
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`jellyfin.ygnv.my.id`)
      kind: Rule
      services:
        - name: jellyfin
          port: 8096
  tls: {}
