# qBittorrent Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
  labels:
    app: qbittorrent
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: qbittorrent
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: reg.ygnv.my.id/docker/linuxserver/qbittorrent:5.1.4
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 64Mi
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 6881
              name: torrent-tcp
              protocol: TCP
            - containerPort: 6881
              name: torrent-udp
              protocol: UDP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Jakarta"
            - name: WEBUI_PORT
              value: "8080"
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            # - name: torrent-watch
            #   mountPath: /watch
      volumes:
        - name: qbittorrent-config
          hostPath:
            path: /mnt/cephfs/docker/media/download/qbittorrent
            type: Directory
        - name: downloads
          hostPath:
            path: /mnt/cephfs/data/downloads
            type: Directory
        # - name: torrent-watch
        #   hostPath:
        #     path: /mnt/cephfs/data/downloads/torrent
        #     type: Directory
---
# qBittorrent Service
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
  labels:
    app: qbittorrent
  annotations:
    metallb.io/address-pool: "main-pool"
    metallb.io/allow-shared-ip: "media"
spec:
  selector:
    app: qbittorrent
  type: LoadBalancer
  loadBalancerIP: 10.1.1.53
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: torrent-tcp
      protocol: TCP
      port: 6881
      targetPort: 6881
    - name: torrent-udp
      protocol: UDP
      port: 6881
      targetPort: 6881
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: media
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`qbittorrent.ygnv.my.id`)
      kind: Rule
      services:
        - name: qbittorrent
          port: 8080
  tls: {}
---
# Qui (qBittorrent Web UI) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qui
  namespace: media
  labels:
    app: qui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: qui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qui
    spec:
      containers:
        - name: qui
          image: reg.ygnv.my.id/ghcr/autobrr/qui:v1.12.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 128Mi
          ports:
            - containerPort: 7476
              name: http
          volumeMounts:
            - name: qui-config
              mountPath: /config
      volumes:
        - name: qui-config
          hostPath:
            path: /mnt/cephfs/docker/media/download/qui
            type: Directory
---
# Qui Service
apiVersion: v1
kind: Service
metadata:
  name: qui
  namespace: media
  labels:
    app: qui
spec:
  selector:
    app: qui
  ports:
    - name: http
      protocol: TCP
      port: 7476
      targetPort: 7476
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qui
  namespace: media
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`qui.ygnv.my.id`)
      kind: Rule
      services:
        - name: qui
          port: 7476
  tls: {}
