apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  namespace: media
  labels:
    app: seerr
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: seerr
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: seerr
    spec:
      containers:
        - name: seerr
          image: reg.ygnv.my.id/ghcr/seerr-team/seerr:v3.1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 256Mi
          ports:
            - containerPort: 5055
          env:
            - name: LOG_LEVEL
              value: info
            - name: TZ
              value: "Asia/Jakarta"
          volumeMounts:
            - name: seerr-config
              mountPath: /app/config
      volumes:
        - name: seerr-config
          persistentVolumeClaim:
            claimName: media-seerr-pvc
---
# Seerr Service
apiVersion: v1
kind: Service
metadata:
  name: seerr
  namespace: media
  labels:
    app: seerr
spec:
  selector:
    app: seerr
  ports:
    - protocol: TCP
      port: 5055
      targetPort: 5055
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seerr
  namespace: media
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`seerr.ygnv.my.id`)
      kind: Rule
      services:
        - name: seerr
          port: 5055
  tls: {}
