# Sonarr Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
  labels:
    app: sonarr
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      nodeSelector:
        kubernetes.io/hperf: "true"
      containers:
        - name: sonarr
          image: reg.ygnv.my.id/docker/linuxserver/sonarr:4.0.16
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 256Mi
          ports:
            - containerPort: 8989
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Jakarta"
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: sonarr-tv
              mountPath: /tv
            - name: sonarr-downloads
              mountPath: /downloads
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: media-sonarr-pvc
        - name: sonarr-tv
          hostPath:
            path: /mnt/cephfs/data/Videos/TV
            type: Directory
        - name: sonarr-downloads
          hostPath:
            path: /mnt/cephfs/data/downloads
            type: Directory
---
# Sonarr Service
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
  labels:
    app: sonarr
spec:
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: media
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`sonarr.ygnv.my.id`)
      kind: Rule
      services:
        - name: sonarr
          port: 8989
  tls: {}
