# Tautulli Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: media
  labels:
    app: tautulli
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: tautulli
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      containers:
        - name: tautulli
          image: reg.ygnv.my.id/ghcr/tautulli/tautulli:v2.16.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 128Mi
          ports:
            - containerPort: 8181
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Jakarta"
          volumeMounts:
            - name: tautulli-config
              mountPath: /config
      volumes:
        - name: tautulli-config
          persistentVolumeClaim:
            claimName: media-tautulli-pvc
---
# Tautulli Service
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: media
  labels:
    app: tautulli
spec:
  selector:
    app: tautulli
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tautulli
  namespace: media
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`tautulli.ygnv.my.id`)
      kind: Rule
      services:
        - name: tautulli
          port: 8181
  tls: {}
