apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secret
  - kubeseal-ui/kubeseal-ui.yml
  - kubeseal-ui/kubeseal-cred.yml
  - kubeseal-ui/ingressroute.yml
  - reloader
  - keel/keel.yml
  - keel/keel-cred.yml
  - keel/notification.yml
