apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: services
  labels:
    app: cloudflared
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
    keel.sh/pollSchedule: "@every 6h"
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cloudflared
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: cloudflared
              topologyKey: kubernetes.io/hostname
      containers:
        - name: cloudflared
          image: reg.ygnv.my.id/docker/cloudflare/cloudflared:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 32Mi
          envFrom:
            - secretRef:
                name: cloudflared-cred
          args:
            - "tunnel"
            - "--no-autoupdate"
            - "--config"
            - "/etc/cloudflared/config.yml"
            - "run"
            - "--metrics"
            - "0.0.0.0:2000"
          ports:
            - containerPort: 2000
              name: metrics
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: cloudflared-config
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cloudflared-hpa
  namespace: services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudflared
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 100
