apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-dump-config
  namespace: services
data:
  mariadb-dump.sh: |
    #!/bin/sh
    apk add --no-cache curl mariadb-client
    set -eo pipefail
    set -o errtrace

    # Discord notification helper
    discord_notify() {
      local status="$1"    # "SUCCESS" or "FAILED"
      local title="$2"
      local description="$3"
      local color=$([ "$status" = "SUCCESS" ] && echo 3066993 || echo 15158332)

      curl -sSL -H "Content-Type: application/json" \
        -X POST "$DISCORD_WEBHOOK_URL" \
        -d "{
          \"embeds\": [{
            \"title\": \"$title\",
            \"description\": \"$description\",
            \"color\": $color
          }]
        }"
    }

    # Global timestamp and cleanup
    TS_INIT=$(date +"%Y-%m-%d %H:%M:%S")
    BACKUP_ROOT="/dumps/$(date +%Y-%m-%d)"
    export MYSQL_PWD=$(cat /etc/creds/password)
    USER=$(cat /etc/creds/username)
    HOST=mariadb

    # Error handler
    fail() {
      TS_FAIL=$(date +"%Y-%m-%d %H:%M:%S")
      DURATION=$(( $(date +%s) - $(date -d "$TS_INIT" +%s) ))
      discord_notify "FAILED" "🚨 Backup FAILED" \
        "**Host:** $HOSTNAME\n**Time:** $TS_FAIL\n**Duration:** ${DURATION}s\n**Error:** Check pod logs for details."
      exit 1
    }
    trap fail ERR

    # Starting notification
    discord_notify "SUCCESS" "🔔 Backup Starting" \
      "**Host:** $HOSTNAME\n**Time:** $TS_INIT\n**Action:** Starting logical backups"

    # Main operations
    mkdir -p "$BACKUP_ROOT"
    DBS=$(mysql -h $HOST -u $USER -sN -e "SHOW DATABASES WHERE \`Database\` NOT IN ('information_schema', 'performance_schema', 'mysql', 'sys')")

    SUMMARY=""
    COUNT=0

    for db in $DBS; do
      COUNT=$((COUNT+1))
      SIZE=$(mysql -h $HOST -u $USER -sN -e "SELECT CONCAT(ROUND(SUM(data_length + index_length) / 1024 / 1024, 2), ' MB') FROM information_schema.TABLES WHERE table_schema = '$db'")
      
      TIMESTAMP=$(date +%H%M%S)
      OUTFILE="$BACKUP_ROOT/${db}_${TIMESTAMP}.sql.gz"
      mysqldump -h $HOST -u $USER --single-transaction --routines --triggers "$db" | gzip > "$OUTFILE"
      FILESIZE=$(du -h "$OUTFILE" | cut -f1)
      sha256sum "$OUTFILE" >> "$BACKUP_ROOT/checksums.sha256"

      SUMMARY="${SUMMARY}• **${db}** — DB size: ${SIZE}, dump: ${FILESIZE}\n"
    done

    # Cleanup old backups
    find /dumps -type f -mtime +7 -delete
    find /dumps -type d -empty -delete

    # Success notification
    TS_END=$(date +"%Y-%m-%d %H:%M:%S")
    DURATION=$(( $(date +%s) - $(date -d "$TS_INIT" +%s) ))
    FINAL_DESC="**Host:** $HOSTNAME\n**Time:** $TS_END\n**Duration:** ${DURATION}s\n\n"
    FINAL_DESC="${FINAL_DESC}${SUMMARY}\n**Total databases:** $COUNT"

    discord_notify "SUCCESS" "✅ All Backups Succeeded" "$FINAL_DESC"
    echo "✅ All done!"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-snapshot-config
  namespace: services
data:
  mariadb-snapshot.sh: |
    #!/bin/sh
    set -euo pipefail

    apk add --no-cache curl zip

    # Discord notification helper
    discord_notify() {
      local status="$1"
      local title="$2"
      local description="$3"
      local color=$([ "$status" = "SUCCESS" ] && echo 3066993 || echo 15158332)
      curl -sSL -H "Content-Type: application/json" \
        -X POST "$DISCORD_WEBHOOK_URL" \
        -d "{\"embeds\":[{\"title\":\"$title\",\"description\":\"$description\",\"color\":$color}]}"
    }

    TS_INIT=$(date +"%Y-%m-%d %H:%M:%S")
    discord_notify "SUCCESS" "🔔 Backup Starting" "**Host:** ${HOSTNAME}\n**Time:** ${TS_INIT}\n**Action:** Starting filesystem backup"

    TIMESTAMP=$(date +%Y%m%d%H%M%S)
    ARCHIVE="/snapshots/mariadb-backup-${TIMESTAMP}.zip"
    cd /mariadadata || exit 1

    if ! zip -rq "$ARCHIVE" .; then
      TS_FAIL=$(date +"%Y-%m-%d %H:%M:%S")
      discord_notify "FAILED" "🚨 Backup FAILED" "**Host:** ${HOSTNAME}\n**Time:** ${TS_FAIL}\n**Error:** Archive creation failed"
      exit 1
    fi

    # Cleanup old backups
    find /snapshots -type f -name '*.zip' -mtime +7 -print -delete
    find /snapshots -type d -empty -print -delete

    TS_END=$(date +"%Y-%m-%d %H:%M:%S")
    FILE_NAME=$(basename "$ARCHIVE")
    FILE_SIZE=$(du -h "$ARCHIVE" | cut -f1)

    SUMMARY="**Host:** ${HOSTNAME}\n**Time:** ${TS_END}\n"
    SUMMARY="${SUMMARY}**Duration:** $(( $(date +%s) - $(date -d "$TS_INIT" +%s) )) seconds\n"
    SUMMARY="${SUMMARY}**Archive:** ${FILE_NAME} (${FILE_SIZE})"

    discord_notify "SUCCESS" "✅ Backup Succeeded" "$SUMMARY"
    echo "✅ Backup completed successfully!"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: services-mariadb-dumps
  namespace: services
spec:
  schedule: "15 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
          - name: mariadb-dumper
            image: reg.ygnv.my.id/docker/Alpine:3.22.0.0
            imagePullPolicy: Always
            env:
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: discord-cred
                  key: DISCORD_URL
            command: ["/bin/sh", "/scripts/mariadb-dump.sh"]
            volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: mariadb-dumps
              mountPath: /dumps
            - name: db-creds
              mountPath: /etc/creds
              readOnly: true
            - name: mariadb-dump-config
              mountPath: /scripts
          volumes:
          - name: mariadb-dump-config
            configMap:
              name: mariadb-dump-config
              defaultMode: 0744
          - name: localtime
            hostPath:
              path: /etc/localtime
              type: File
          - name: mariadb-dumps
            hostPath:
              path: /mnt/cephfs/docker/services/mariadb/backup/dumps
              type: Directory
          - name: db-creds
            secret:
              secretName: mariadb-cred
              items:
              - key: username
                path: username
              - key: password
                path: password
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: services-mariadb-snapshots
  namespace: services
spec:
  schedule: "45 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
          - name: mariadb-snapshotter
            image: reg.ygnv.my.id/docker/Alpine:3.22.0
            imagePullPolicy: Always
            env:
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: discord-cred
                  key: DISCORD_URL
            command: ["/bin/sh", "/scripts/mariadb-snapshot.sh"]
            volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: mariadb-data
              mountPath: /mariadadata
              readOnly: true
            - name: mariadb-snapshots
              mountPath: /snapshots
            - name: mariadb-snapshot-config
              mountPath: /scripts
          volumes:
          - name: localtime
            hostPath:
              path: /etc/localtime
              type: File
          - name: mariadb-snapshot-config
            configMap:
              name: mariadb-snapshot-config
              defaultMode: 0744
          - name: mariadb-data
            hostPath:
              path: /mnt/cephfs/docker/services/mariadb/data
              type: Directory
          - name: mariadb-snapshots
            hostPath:
              path: /mnt/cephfs/docker/services/mariadb/backup/snapshots
              type: Directory
          restartPolicy: Never

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ghostdb-dump-config
  namespace: services
data:
  ghostdb-dump.sh: |
    #!/bin/sh
    apk add --no-cache curl mysql-client
    set -eo pipefail
    set -o errtrace

    discord_notify(){
      local status="$1"; local title="$2"; local description="$3"
      local color=$([ "$status" = "SUCCESS" ] && echo 3066993 || echo 15158332)
      curl -sSL -H "Content-Type: application/json" \
        -X POST "$DISCORD_WEBHOOK_URL" \
        -d "{\"embeds\":[{\"title\":\"$title\",\"description\":\"$description\",\"color\":$color}]}"
    }

    TS_INIT=$(date +"%Y-%m-%d %H:%M:%S")
    BACKUP_ROOT="/dumps/$(date +%Y-%m-%d)"
    export MYSQL_PWD=$(cat /etc/creds/password)
    USER=$(cat /etc/creds/username)
    HOST=ghostdb

    fail(){
      TS_FAIL=$(date +"%Y-%m-%d %H:%M:%S")
      DURATION=$(( $(date +%s) - $(date -d "$TS_INIT" +%s) ))
      discord_notify "FAILED" "🚨 Dump FAILED" \
        "**Host:** $HOSTNAME\n**Time:** $TS_FAIL\n**Duration:** ${DURATION}s\n**Error:** Check logs."
      exit 1
    }
    trap fail ERR

    discord_notify "SUCCESS" "🔔 MySQL Backup Starting" \
      "**Host:** $HOSTNAME\n**Time:** $TS_INIT\n**Action:** Starting logical dumps"

    mkdir -p "$BACKUP_ROOT"
    DBS=$(mysql -h $HOST -u $USER -sN -e "SHOW DATABASES WHERE \`Database\` NOT IN ('information_schema','performance_schema','mysql','sys');")

    SUMMARY=""; COUNT=0
    for db in $DBS; do
      COUNT=$((COUNT+1))
      SIZE=$(mysql -h $HOST -u $USER -sN \
        -e "SELECT CONCAT(ROUND(SUM(data_length+index_length)/1024/1024,2),' MB') \
        FROM information_schema.TABLES WHERE table_schema='$db';")
      TIMESTAMP=$(date +%H%M%S)
      OUT="$BACKUP_ROOT/${db}_${TIMESTAMP}.sql.gz"
      mysqldump -h $HOST -u $USER --single-transaction --routines --triggers "$db" \
        | gzip > "$OUT"
      FILESIZE=$(du -h "$OUT" | cut -f1)
      sha256sum "$OUT" >> "$BACKUP_ROOT/checksums.sha256"
      SUMMARY="${SUMMARY}• **${db}** — DB size: ${SIZE}, dump: ${FILESIZE}\n"
    done

    find /dumps -type f -mtime +7 -delete
    find /dumps -type d -empty -delete

    TS_END=$(date +"%Y-%m-%d %H:%M:%S")
    DURATION=$(( $(date +%s) - $(date -d "$TS_INIT" +%s) ))
    FINAL="**Host:** $HOSTNAME\n**Time:** $TS_END\n**Duration:** ${DURATION}s\n\n${SUMMARY}**Total databases:** $COUNT"
    discord_notify "SUCCESS" "✅ MySQL Dumps Succeeded" "$FINAL"
    echo "✅ Logical dumps complete"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ghostdb-snapshot-config
  namespace: services
data:
  ghostdb-snapshot.sh: |
    #!/bin/sh
    set -euo pipefail
    apk add --no-cache curl zip

    discord_notify(){
      local status="$1"; local title="$2"; local description="$3"
      local color=$([ "$status" = "SUCCESS" ] && echo 3066993 || echo 15158332)
      curl -sSL -H "Content-Type: application/json" \
        -X POST "$DISCORD_WEBHOOK_URL" \
        -d "{\"embeds\":[{\"title\":\"$title\",\"description\":\"$description\",\"color\":$color}]}"
    }

    TS_INIT=$(date +"%Y-%m-%d %H:%M:%S")
    discord_notify "SUCCESS" "🔔 Filesystem Backup Starting" \
      "**Host:** ${HOSTNAME}\n**Time:** ${TS_INIT}\n**Action:** FS snapshot"

    TIMESTAMP=$(date +%Y%m%d%H%M%S)
    ARCHIVE="/snapshots/ghostdb-backup-${TIMESTAMP}.zip"
    cd /ghostdbdata || exit 1

    if ! zip -rq "$ARCHIVE" .; then
      TS_FAIL=$(date +"%Y-%m-%d %H:%M:%S")
      discord_notify "FAILED" "🚨 Snapshot FAILED" \
        "**Host:** ${HOSTNAME}\n**Time:** ${TS_FAIL}\n**Error:** archive failed"
      exit 1
    fi

    find /snapshots -type f -name '*.zip' -mtime +7 -print -delete
    find /snapshots -type d -empty -print -delete

    TS_END=$(date +"%Y-%m-%d %H:%M:%S")
    SIZE=$(du -h "$ARCHIVE"|cut -f1)
    DUR=$(( $(date +%s) - $(date -d "$TS_INIT" +%s) ))
    SUMMARY="**Host:** ${HOSTNAME}\n**Time:** ${TS_END}\n**Duration:** ${DUR}s\n**Archive:** $(basename "$ARCHIVE") (${SIZE})"
    discord_notify "SUCCESS" "✅ Snapshot Succeeded" "$SUMMARY"
    echo "✅ Filesystem snapshot complete"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: services-ghostdb-dumps
  namespace: services
spec:
  schedule: "17 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
          - name: ghostdb-dumper
            image: reg.ygnv.my.id/docker/Alpine:3.22.0.0
            imagePullPolicy: Always
            env:
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: discord-cred
                  key: DISCORD_URL
            command: ["/bin/sh", "/scripts/ghostdb-dump.sh"]
            volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: ghostdb-dumps
              mountPath: /dumps
            - name: db-creds
              mountPath: /etc/creds
              readOnly: true
            - name: ghostdb-dump-config
              mountPath: /scripts
          volumes:
          - name: ghostdb-dump-config
            configMap:
              name: ghostdb-dump-config
              defaultMode: 0744
          - name: localtime
            hostPath:
              path: /etc/localtime
              type: File
          - name: ghostdb-dumps
            hostPath:
              path: /mnt/cephfs/docker/services/ghost/mysql-backup/dumps
              type: Directory
          - name: db-creds
            secret:
              secretName: ghost-cred
              items:
              - key: dbuser
                path: username
              - key: dbpass
                path: password
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: services-ghostdb-snapshots
  namespace: services
spec:
  schedule: "45 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
          - name: ghostdb-snapshotter
            image: reg.ygnv.my.id/docker/Alpine:3.22.0.0
            imagePullPolicy: Always
            env:
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: discord-cred
                  key: DISCORD_URL
            command: ["/bin/sh", "/scripts/ghostdb-snapshot.sh"]
            volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: ghostdb-data
              mountPath: /ghostdbdata
              readOnly: true
            - name: ghostdb-snapshots
              mountPath: /snapshots
            - name: ghostdb-snapshot-config
              mountPath: /scripts
          volumes:
          - name: localtime
            hostPath:
              path: /etc/localtime
              type: File
          - name: ghostdb-snapshot-config
            configMap:
              name: ghostdb-snapshot-config
              defaultMode: 0744
          - name: ghostdb-data
            hostPath:
              path: /mnt/cephfs/docker/services/ghost/mysql
              type: Directory
          - name: ghostdb-snapshots
            hostPath:
              path: /mnt/cephfs/docker/services/ghost/mysql-backup/snapshots
              type: Directory
          restartPolicy: Never
