---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-cred
  namespace: services
spec:
  encryptedData:
    DISCORD_URL: AgCUM+qAqKOMjBNB2kLA/e9Xp3MlZYXLM1w8uRejlQO6pMdDkcTAPONdCG6BOqryLd+WUxlegvx5uczKPUWPnYSzs9/6XoUfykyN5Ij8qU5lhJo+Wjde8ETGirZ8QbktjVm88JByv/jy3duu9edo/lo4qNp0u3iTaE2zbeIjmKP2BlhjDAv0VgJAqylLZvoiiJvSludByNax1Gu9XfbTVyJkYUEHZJ37APdr2i8DxhITI1opJIMgVW3uzZJkDt8RwHBZl5JhcuNXc+p5ZLKGHANg+t+yfEwPtpc8PK9K4xlzvZnUrkxyLCUKgUymz5L+CswThvLgxzCWqMc5M/WF/Qsa6J4p1R/G1eULnFcl953dI7x0xO23khBE76yGIGDvxHjlokAJCeszlPRN4OZxy5UpJt+gRIY9GTlbVCd2AZUmKi9bOfQWUXzfsY1bKbODAGQCFISs8xXdGQPLpgzV9lXRQYrXMo0WWA5TG4FXEBNKYOyGruR8wK/4p5YT38GihrpO3ILjHi0hN2w6+iVLsubQSmAVUgW7wnHfyeO0Et2/mymuiXjBQwlP4HBgs8ccde/qrlGmdt4S5/P0AzEA5ITI7y1kpDvk/cUnGb1RrYWJW2TOIZt9ceuWUjuL4aSW8j2xaEqhhpz+oK+Cq/6IQBcsE5Ln2hzXLR1s/kiQuaZansP7uP4as8b2FHC6BuBhd8lJOVPnhallApxvb34+FJUheZS5L29keFwE7ubLOLGruCBycL9YaYhPQSvb0DeeZWfUpIhcLccWoHlvxbpuhu4v28YksKXVMt5gej5FIHcC9H6El3qz0b5Fvy3PR0o4+61tTb7EXFntwu1CK9JZn4arnFipdmvfUDDh
  template:
    metadata:
      creationTimestamp: null
      name: discord-cred
      namespace: services
    type: Opaque
