apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecoguardian
  namespace: services
  labels:
    app: ecoguardian
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll 
    keel.sh/match-tag: "true"
    keel.sh/pollSchedule: "@every 6h"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ecoguardian
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ecoguardian
    spec:
      nodeSelector:
        kubernetes.io/disk: hdd
      containers:
      - name: ecoguardian
        image: ghcr.io/yoganovvaindra/ecoguardian-web:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 512Mi
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ecoguardian-cred
              key: db-url
        - name: NEXTAUTH_URL
          value: "https://ecoguardian.yoganova.my.id"
        - name: NEXT_PUBLIC_SITE_URL
          value: "https://ecoguardian.yoganova.my.id"
        - name: NEXT_PUBLIC_CHART_URL
          value: "https://ecochart.yoganova.my.id"
        - name: GOOGLE_CLIENT_ID
          value: ""
        - name: GOOGLE_CLIENT_SECRET
          value: ""
        volumeMounts:
        - name: images
          mountPath: /app/images
      volumes:
      - name: images
        hostPath:
          path: /mnt/cephfs/docker/services/ecoguardian/images
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: ecoguardian
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: ecoguardian
  ports:
  - name: ecoguardian
    port: 3000
    targetPort: 3000
---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: ecoguardian-binding
  namespace: services
spec:
  tunnelRef:
    kind: ClusterTunnel
    name: tunnel-yoganova
  subjects:
    - name: ecoguardian
      spec:
        fqdn: ecoguardian.yoganova.my.id
        protocol: http
    - name: ecoguardian
      spec:
        fqdn: ecochart.yoganova.my.id
        protocol: http
