apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: services
data:
  my.cnf: |
    [mysqld]
    # Insert your MySQL configuration settings here
    performance_schema = off
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: services
  labels:
    app: ghost
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: reg.ygnv.my.id/docker/ghost:5.121.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
        ports:
        - containerPort: 2368
        env:
          - name: database__client
            value: "mysql"
          - name: database__connection__host
            value: "ghost-db"
          - name: database__connection__port
            value: "3306"
          - name: database__connection__user
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: dbuser
          - name: database__connection__password
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: dbpass
          - name: database__connection__database
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: dbname
          - name: mail_service
            value: "brevo"
          - name: mail_from
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: mail
          - name: mail_transport
            value: "SMTP"
          - name: mail_options_host
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: mailhost
          - name: mail_options_port
            value: "587"
          - name: mail_options_auth_user
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: mailauth
          - name: mail_options_auth_pass
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: mailpass
          - name: url
            value: "https://ygnv.my.id"
        volumeMounts:
          - name: ghost-data
            mountPath: /var/lib/ghost/content
      volumes:
        - name: ghost-data
          hostPath:
            path: /mnt/cephfs/docker/services/ghost/data
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: ghost
  ports:
  - name: ghost
    port: 2368
    targetPort: 2368
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ghost-db
  namespace: services
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ghost-db
  template:
    metadata:
      labels:
        app: ghost-db
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      terminationGracePeriodSeconds: 10
      containers:
      - name: ghost-db
        image: reg.ygnv.my.id/docker/mysql:9.3.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: sqlpass
          - name: TZ
            value: "Asia/Jakarta"
        volumeMounts:
          - name: ghost-db-data
            mountPath: /var/lib/mysql
          - name: ghost-db-config
            mountPath: /etc/mysql/conf.d/my.cnf
            subPath: my.cnf
      volumes:
        - name: ghost-db-data
          hostPath:
            path: /mnt/cephfs/docker/services/ghost/mysql
            type: Directory
        - name: ghost-db-config
          configMap:
            name: mysql-config
            items:
              - key: my.cnf
                path: my.cnf
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-db
  namespace: services
spec:
  selector:
    app: ghost-db
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  clusterIP: None
