apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: services
data:
  my.cnf: |
    [mysqld]
    # Insert your MySQL configuration settings here
    performance_schema = off
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: services
  labels:
    app: ghost
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: reg.ygnv.my.id/docker/ghost:6.2.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 256Mi
        ports:
        - containerPort: 2368
        env:
          - name: database__client
            value: "mysql"
          - name: database__connection__host
            value: "ghostdb"
          - name: database__connection__port
            value: "3306"
          - name: database__connection__user
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: dbuser
          - name: database__connection__password
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: dbpass
          - name: database__connection__database
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: dbname
          - name: mail__service
            value: "Mailgun"
          - name: mail__from
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: mailfrom
          - name: mail__transport
            value: "SMTP"
          - name: mail__options__host
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: mailhost
          - name: mail__options__port
            value: "587"
          - name: mail__options__auth__user
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: mailauth
          - name: mail__options__auth__pass
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: mailpass
          - name: url
            value: "https://ygnv.my.id"
        volumeMounts:
          - name: ghost-data
            mountPath: /var/lib/ghost/content
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
      volumes:
        - name: ghost-data
          hostPath:
            path: /mnt/cephfs/docker/services/ghost/data
            type: Directory
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
---
apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: ghost
  ports:
  - name: ghost
    port: 2368
    targetPort: 2368
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ghostdb
  namespace: services
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ghostdb
  template:
    metadata:
      labels:
        app: ghostdb
    spec:
      nodeSelector:
        kubernetes.io/hperf: "true"
      terminationGracePeriodSeconds: 10
      containers:
      - name: ghostdb
        image: reg.ygnv.my.id/docker/mysql:9.4.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 256Mi
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ghost-cred
                key: sqlpass
          - name: TZ
            value: "Asia/Jakarta"
        volumeMounts:
          - name: ghostdb-data
            mountPath: /var/lib/mysql
          - name: ghostdb-config
            mountPath: /etc/mysql/conf.d/my.cnf
            subPath: my.cnf
      volumes:
        - name: ghostdb-data
          hostPath:
            path: /mnt/cephfs/docker/services/ghost/mysql
            type: Directory
        - name: ghostdb-config
          configMap:
            name: mysql-config
            items:
              - key: my.cnf
                path: my.cnf

---
apiVersion: v1
kind: Service
metadata:
  name: ghostdb
  namespace: services
spec:
  selector:
    app: ghostdb
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  clusterIP: None
