apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: services
  labels:
    app: portfolio
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: portfolio
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: ghcr.io/yoganovvaindra/portfolio:v0.1.6
        imagePullPolicy: Always
        resources:
          requests:
            memory: 32Mi
        ports:
        - containerPort: 80
        env:
        - name: TZ
          value: Asia/Jakarta
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: services
  labels:
    app: portfolio
spec:
  type: ClusterIP
  selector:
    app: portfolio
  ports:
  - port: 80
    targetPort: 80