apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: services
  labels:
    app: portfolio
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: portfolio
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: reg.ygnv.my.id/ghcr/yoganovvaindra/portfolio:v0.1.9
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
        ports:
        - containerPort: 80
        env:
        - name: TZ
          value: Asia/Jakarta
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: services
  labels:
    app: portfolio
spec:
  type: ClusterIP
  selector:
    app: portfolio
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: portfolio-hpa
  namespace: services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: portfolio
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100