apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/aquasecurity/trivy-operator/v0.26.1/deploy/static/trivy-operator.yaml
# namespace: trivy-system
patches:
  - path: operator-config.yml
    target:
      kind: ConfigMap
      name: trivy-operator-config
      namespace: trivy-system
  - path: trivy-config.yml
    target:
      kind: ConfigMap
      name: trivy-operator-trivy-config
      namespace: trivy-system
  - patch: |-
      - op: remove
        path: /data/trivy.resources.limits.cpu
      - op: remove
        path: /data/trivy.resources.limits.memory
    target:
      kind: ConfigMap
      name: trivy-operator-trivy-config
      namespace: trivy-system
  - path: operator-deployment.yml
    target:
      kind: Deployment
      name: trivy-operator
      namespace: trivy-system
  - patch: |-
      - op: remove
        path: /spec/template/spec/volumes/0/emptyDir
    target:
      kind: Deployment
      name: trivy-operator
      namespace: trivy-system