apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator-trivy-config
  namespace: trivy-system
data:
  trivy.timeout: "10m0s"
  trivy.resources.requests.cpu: "200m"
  trivy.resources.requests.memory: "256M"