apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: immich
  labels:
    app: immich
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: immich
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: immich
    spec:
      nodeSelector:
        kubernetes.io/hperf: "true"
      containers:
      - name: immich
        image: ghcr.io/imagegenius/immich:1.132.1-openvino
        imagePullPolicy: Always
        resources:
          requests:
            memory: 512Mi
        ports:
        - containerPort: 8080
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Asia/Jakarta"
        - name: SERVER_PORT
          value: "8080"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: password
        - name: DB_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: dbname
        - name: DB_HOSTNAME
          value: "immich-db"
        - name: DB_PORT
          value: "5432"
        - name: REDIS_HOSTNAME
          value: "immich-valkey"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: ""
        - name: MACHINE_LEARNING_HOST
          value: "0.0.0.0"
        - name: MACHINE_LEARNING_PORT
          value: "3003"
        - name: MACHINE_LEARNING_WORKERS
          value: "1"
        - name: MACHINE_LEARNING_WORKER_TIMEOUT
          value: "120"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: photos-volume
          mountPath: /photos
        - name: pictures-volume
          mountPath: /photos/pictures
          readOnly: true
        # Add device mounts
        - mountPath: /dev/dri
          name: dri-device
        - mountPath: /dev/bus/usb
          name: usb-devices
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        supplementalGroups: [44]  # Video group for GPU access
      volumes:
      - name: config-volume
        hostPath:
          path: /mnt/cephfs/docker/immich/config
          type: Directory
      - name: libraries-volume
        hostPath:
          path: /mnt/cephfs/docker/immich/libraries
          type: Directory
      - name: photos-volume
        hostPath:
          path: /mnt/cephfs/docker/immich/photos
          type: Directory
      - name: pictures-volume
        hostPath:
          path: /mnt/Data/Pictures
          type: Directory
      # Add device volumes
      - name: dri-device
        hostPath:
          path: /dev/dri
      - name: usb-devices
        hostPath:
          path: /dev/bus/usb
---
apiVersion: v1
kind: Service
metadata:
  name: immich-svc
  namespace: immich
spec:
  selector:
    app: immich
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich
  namespace: immich
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`immich.ygnv.my.id`)
      kind: Rule
      services:
        - name: immich-svc
          port: 8080
  tls:
    certResolver: cloudflare
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: immich
  labels:
    app: valkey
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: valkey
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
      - name: valkey
        image: valkey/valkey:8.1-alpine
        imagePullPolicy: Always
        resources:
          requests:
            memory: 64Mi
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: valkey-data
          mountPath: /data
      volumes:
      - name: valkey-data
        hostPath:
          path: /mnt/cephfs/docker/immich/valkey
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: immich-valkey
  namespace: immich
spec:
  selector:
    app: valkey
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: immich
  labels:
    app: db
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: db
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: db
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      terminationGracePeriodSeconds: 10
      containers:
      - name: db
        image: tensorchord/pgvecto-rs:pg16-v0.2.1
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: dbname
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        hostPath:
          path: /mnt/cephfs/docker/immich/postgres16
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: immich-db
  namespace: immich
spec:
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
