apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tet
  namespace: immich
spec:
  encryptedData:
    key: AgAJhRliPLbIJL53k9fISOk7rnnERJYE92fMU59t3Xr2/GtD+5pUxGV/c840ho87b2oDShp7jD+jcBefi3a2f6XutluYHxPI0ttBvjBTnR+0EpRw7P5VcILf2LdssZDpVpussTWgKpULZolvGVMxk5v41PXqCGNerO6MOuingepZUv7mNIYzEH0dfA40z7lBJMqPm4rz0P8fJHqGkqEFbBO+K5mD/TtK098pguf1eYefa5A5GBOVpE/C+vvdvv8mYQP+Pkc1QW0TM625uf/qG6Pm+yp8C/1lfVld4iWYXuVJl6BhrlH7SDcgYcgpuYfFzkLwIFRjpQuJ3LEE/5hkwFwLkk14cAajGG7HNYVwGXyG3o9PUBGQkiGyGbdyadTzGpYpprHVnZFKB9Dyn1bsI/prDRf8b0p59ae5xzBIk0naaN4WigY1IcjanyN74lzZ8jKRoZvkDqIG+UMz0pzVcw4g1ynA7G6jR7eKaEbznA72RArTDVF723BJj0k93NB9bgNL4M58tQwDGntgxUpgAk5cN3IR0W9ECkCEo/7uWJYgYZlpOeJE/60+I0a5N8XV5PXwzCyVZyiXzhfVsgB7P/KSjTj8PHjzgbHk0zWawX5l08w/K0Ba9YFDEfm/3RQKl+He2SpuzFTIx9prVH8H/Jle5c34rTQqexc1D6tyMvqtvQzA6EED9GayzwaG1auQT/egHg==
  template:
    metadata:
      name: tet
      namespace: immich
    type: Opaque
