apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tet
  namespace: immich
spec:
  encryptedData:
    ffghhff: AgCsARMMC68F0qA7SqYhTewMpc00gEjEpJzhVJxM+iKXY/BiHnXA+e53zszmfIxu9Pwg0JOZ1AJDUC8Cl7phra+9JJPXMEZPVWLnPva2Z8FenOua/yXBkPfsX3GJTweakxRjorb5sunjthvu1g95+2bXJaHs/eDg/YAWCQ3Eb3uGVq1NZKfR6euV0N1PJf10dOT51HeOrkp/WtZvLUoW7qdPAFZMveu7eVjogAfQBeyTvTOunJxW/7uOl/pr6IZGQ2gXGtpjfVDmBQaEp8ENB0XqsQPtmqlgZRs452L94uAbDuz5X7JRSvOxCONuDr4LmvTZzWZtip59aU1zAOv8+ABbk5vNKMg47c3LTRDsvAUdFchBiAs+PFdbHHharpO40u8XCdbb/fEtk23kRE6OSFuAN1JjgnI8G56qDoQ1riAgUpRgoECKdhDtvP23GWPZf9eS9kKttvp0V0Ccfkjr9xUcs/xDMjCmNWJJAsOmgpzx01WZLsI1o8IK2tPuTzws7u55WX+l5VKEplT2mRRblL6zWXT1ng6Xb40j0sJIKn/GGXxET4xLJ2orES96Ou8BhbHZvGAGknLMuEDyLQP0+Qr4ImT2TZLZ+cwQOu6K/xjSEH3yegoYayjOrC3A1FMPvhZGnUhnYrY7kgAlk9oCbklf3fXLKDg6Chj3ResdNqUGGVutldhNMBt3/7uCgR6CJtKPbLhSf3nGqyirFdYpsM9wzpDgGL9V
    key: AgCDJVq57eHAPyLgTO2luJMKxmop7T9sNOGtJ4Lep2VEAx+TD6M1xadus4I/jblOJF2F61wTAj5FDWffN0Ty4tvoBiVKUM8TO4VVP8HS5YWTLAGtz9Hqyi0UPp4XOCi15VT2svUcJQX2GjxikassZIH26fzkn0aucSYZ8L97LTCaTP9pc7wTAkiKSCS7kSnhtlW6yhUkL0QamJsU2s69ru5iNAzImAqzcXABUg1xai6ECDbVMK634afJBYrJzK3bQlWhHjIRRBzVlXAIxsCjZasHxzN+Ups7x0XhMNTt4Xffwu3M3002fRllNvbA88T2otwE/4Cnvh979Gd5/7lClBT12LgyFTpcojnWA+Obh4dLRURt8h/Kwla1hUSrt8aFTurPGMdTNhP9HUS2oByVWCs82CZqRrnWhBKpvZ48U3tNlts+rPUqFsh6J0IYPTVCGA2Me2gM1tVx4M8aAmlTawba4yaOZn32XEf7435HnWiOmMtMYEQMyWvjmS4rRUAYXlDK/o+/VlvETWWt3T8rQbd+lr9O7im6AqVIa+OEb+UbVbVNk+gRze4W5nB5VE+jqrw3iKQBjYOMjjuA2fIP2mZZaGDbHuHNQkrR/nU6Ie/T+H3NtdlISKmRM5fKvROOiPXG0RvAJ+tChoRhVzrIFAvvbDFJmmnjcyOVhNP1cTXSI1Ky1UxwkRu0E+BWx8BKgvbYf7LhtWU=
  template:
    metadata:
      name: tet
      namespace: immich
    type: Opaque
