{
 "title": "Multiple OpenWRT infrastructure",
 "description": "A dashborad for VPN infrastructure composed of multiple OpenWRT devices.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",nodename=~\"$host\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$node\",job=~\"$job\"} and (up{instance=~\"$node\",job=~\"$job\"} or on() vector(0))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Status Trace",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "up{instance=~\"$node\",job=~\"$job\"} and (up{instance=~\"$node\",job=~\"$job\"} or on() vector(0))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Network Traffic",
   "type": "piechart",
   "description": "Total network traffic",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance)(node_network_transmit_bytes_total{instance=~\"$node\",job=~\"$job\"}) + sum by(instance)(node_network_receive_bytes_total{instance=~\"$node\",job=~\"$job\"})) / 1024 / 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAN Transfer Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=~\"^(home|br-lan)\",instance=~\"$node\",job=~\"$job\"}/1024/1024",
     "legendFormat": "TX - {{instance}}"
    },
    {
     "expr": "-(node_network_transmit_bytes_total{device=~\"^(home|br-lan)\",instance=~\"$node\",job=~\"$job\"})/1024/1024",
     "legendFormat": "RX - {{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count by (instance)(count by (cpu,instance)(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"})) - avg by (instance)(sum by (mode,instance)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",job=~\"$job\"}[5m])))) / count by (instance)(count by (cpu,instance)(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "bargauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VPN Transfer Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=\"home\",instance=~\"$node\",job=~\"$job\"}/1024/1024",
     "legendFormat": "TX - {{instance}}"
    },
    {
     "expr": "-(node_network_transmit_bytes_total{device=\"home\",instance=~\"$node\",job=~\"$job\"})/1024/1024",
     "legendFormat": "RX - {{instance}}"
    }
   ]
  },
  {
   "title": "LAN Transfer Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=\"br-lan\",instance=~\"$node\",job=~\"$job\"}/1024/1024",
     "legendFormat": "TX - {{instance}}"
    },
    {
     "expr": "-(node_network_transmit_bytes_total{device=\"br-lan\",instance=~\"$node\",job=~\"$job\"})/1024/1024",
     "legendFormat": "RX - {{instance}}"
    }
   ]
  },
  {
   "title": "WIFI Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance)(wifi_stations{instance=~\"$node\",job=~\"$job\"} or on() vector(0))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "core(s)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (instance)(count by(cpu,instance)(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic Trace (MB)",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(sum by (instance)(irate(node_network_transmit_bytes_total{instance=~\"$node\",job=~\"$job\",device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m])) + sum by(instance)(irate(node_network_receive_bytes_total{instance=~\"$node\",job=~\"$job\",device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]))) / 1024 / 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Wifi Quality",
   "type": "stat",
   "description": "average Wifi quality",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance)(wifi_network_quality{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Architectures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "node_openwrt_info{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "CPU Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Basic ($node)",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic ($node)",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node\",job=~\"$job\"} - (node_memory_Cached_bytes{instance=~\"$node\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  { "title": "WiFi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "WiFi Network Quality ($node)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "wifi_network_quality{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{ifname}}"
    }
   ]
  },
  {
   "title": "WiFi Bitrate ($node)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "wifi_network_bitrate{instance=~\"$node\",job=~\"$job\"}/1024",
     "legendFormat": "{{ifname}}"
    }
   ]
  },
  {
   "title": "WiFi Station Signal ($node)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "wifi_station_signal_dbm{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{mac}} # {{ifname}}"
    }
   ]
  },
  {
   "title": "WiFi Network Noise ($node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "wifi_network_noise_dbm{instance=~\"$node\",job=~\"$job\"}"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Network Traffic by Bytes ($node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$node\",job=~\"$job\"}[5m])/1024",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node\",job=~\"$job\"}[5m])/1024",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Receive Bytes Total ($node)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{instance=~\"$node\",job=~\"$job\"}/1024/1024",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit Bytes Total ($node)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "-node_network_transmit_bytes_total{instance=~\"$node\",job=~\"$job\"}/1024/1024",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Top NAT Traffic ($node)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 94 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "topk(15, node_nat_traffic{instance=~\"$node\",job=~\"$job\"}/1024/1024)",
     "legendFormat": "Dest= {{dest}} # Source= {{src}}"
    }
   ]
  }
 ]
}