apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: uptime-kuma
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: reg.ygnv.my.id/docker/louislam/uptime-kuma:2.0.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 256Mi
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: data
              mountPath: /app/data
          # env:
          #   - name: UPTIME_KUMA_PORT
          #     value: "3001"
      volumes:
        - name: data
          hostPath:
            path: /mnt/cephfs/docker/monitoring/uptime-kuma
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: monitoring
  labels:
    app: uptime-kuma
spec:
  selector:
    app: uptime-kuma
  ports:
    - port: 3001
      targetPort: 3001
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma
  namespace: monitoring
  labels:
    app: uptime-kuma
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`uptime.ygnv.my.id`)
      kind: Rule
      services:
        - name: uptime-kuma
          port: 3001
  tls:
    secretName: ygnv-wildcard-cert

