apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: gitops
    repoURL: https://github.com/YogaNovvaindra/kube.git
    targetRevision: HEAD
  sources: []
  project: local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true