---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/patch: "true"
spec:
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
    type: Opaque
  encryptedData:
    oidc.authentik.clientID: AgCCMI8CVH+yaLwsS105ZS51EsSsozIqp5k147yOH3eGgtG2ASxpS7KL95piOVnJscQnS+te9W14pwNSc4Szg9Kv9EbWS3m1OzpffNY2TUny/xuce7mNb2vQjqJqIUeXx1CWy9c3V7kS6PNA+nnaRUTd0HeewlDKbgvvXAaVPzNbI2++kX9gR2BCol4fNAOtlS/1OZyPTmHIai49YOioaPy7R2avD1mGLXpyaOjRdmjS7Q9KlEtulTGU3pET0+fOWiPUp5EvympJlMMuuMYIJ0hPXdMqZB8Q4bvYxcNXu7CaJh0lzEu29Wm1bB1nSnYgLrAqoPrq3LMz2TKdKh5OAoQGo6lO2UO0vRY6KDMNgTxXBod8Z3J1SISG+XQAzBw6GOMtjjdrbRZUMhKWYUUi6UWbaTzeb8oeAES/+CcUwJnkqaBZJ2F83IGg3wqAMSEITM0orlhLzPsWn5zjMkl41brH7G+tWskSn8lD8rB00JeACqI2roBzp+tEcd7QJ2s9F9KzO1o5EaQ6m4CCLvTET54F0wjoXQ2o//lwXofJ6erpuUeWgeIx9WSr1xmyUE1XCgH63T2l53oZ8w+KqeZhwYcRq0NetIXoZNIp2sz07FE2aPKitMaTU3d5P5NoRDhd2OPgbOBQrr+I26WXGxz48JX4r6IahPSLFyPXRkfBS3nQtpGWVLiIunQr8eqEshoCGBSAy3/apKkvax1cGBid9Cbep+g0esngl5WEVgED+JQMQg/jdo4JAkCM
    oidc.authentik.clientSecret: AgCSiLYWG/7ty2skbs81o4JqqUxdWkqfZ9y4QOQ2UTMzd64DITKTrrAa4sa9iPpZ/O0ezABB0y+bNQG03cXPIi1xluZeC7s8WtuwKYRpeO0o5EuupwtRN30w9GNyKsqmn8dVbcHb0HURgVXpr7HZP76z3hHZ0OY1cFnKSBLgz93T3XoXBDggfjJduV1M6Px42gsXqyMco+EK5uDcdqveFsL+6YIlkB/LP8kQUyRx/9yEt1+FkxXpOVcJqji6Y83k1JwlYrSnlhA5EDRMsfpY1aGUmxJhvC5sMfCRbmUULpNXpFYifxw1i67Lg3g9R9aXN8A8Z8bFg3Hxpqok0fFVRpDgnow+0nc1+BSToweyVbEqVKu2fCXTeLJ1PaqC5WBJp8YPU7KXzgnbzCVRN8A/ZVkKd2HTibb+JWPFx42Ocx26GqDPk8JGWtJemnWErW1XNZmnUD966ToeX0ogj8Wsb38nuB+3sAHeruEZ7WIXyOAD3dIh8EtrjBZT81Ej33EvBEfK2s6OBtgHd+BWfgxgaWDo5jQrVUIUdHj1NKDzzg/35KdL6VtmeZQUQlTF53RcVEPxKmcJ/WJsp4LuBP5ZcFXWhriSDPtuI1XXwxvT8wlSNuppWFPtQ9Hby+6LTFEQr1ql7sgXafVP0voj56q5YkdQV2pMjBi9qhypZjnQY0SvLkuPgAX2pIBGZ+At9KQwKYdmmHqOQ7NhmnnwbnR532tauYde3tW4J7+lUpaiwTbiasq9qYQetVw7pPP9r4taut0SyaXVArMibntYPqq8dNlgh8YYX/yV6Mbc5062FQNu0CSDgXCe0RxvIxEsJEDsBHDwZfbZ5tpgmuqa7KrMAxW7PzXOKRcE6NabTTaGhBfFyA==
