---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/patch: "true"
spec:
  encryptedData:
    oidc.authentik.clientID: AgBzJS+WWgGwT6OPgKW/NQvaZ34ZVCTzfHKDZgyP90VuXJJu7ITa52olvb9cu3ZvPDlygDKdQY1H85rcfAwwxM1wDLXQcW03RQe+T3UgwgHn0FphmT2bZ3wQB0piygccnqxIYSTjIWMfnYjqS+IzY+ghn2VWAUCyNvV/+5N493xy9+WFGfi+a3HDneahOMBQXUwd7MrykTxK8BnFFKD4r0T9D1C93AfjSsoF2cRhORJ1jrP3vkjTghF5+oPLp8y4Xrc7nVf4AN5/etw5X/YDT5UOv7vC8VCHrNSWkW3jexu8oR18Oqq7WxQaqNlLH9NdtEQxEHGooTEtJ4TxIH8uN+QFMTji8Q54CjihpQ1+ItD6nN1YIVGtpaZwkK8psJ3l6RFQb2wm+J1xV43PPUW2En+h80msotfM7SrqIoVxAgKaQtYAJu3d57j/WsuVzTn4TRLQOehIHFsPQNiVUqozLzw0kWE3Cmm7g+LI8P3x+ulhy2I992/fchElhQLO+4Xlwz2R19u8lKaapdYhgUEQNFl3wdYT0nTB0hSVdKnoYsx6Y10psyQ7uYOCOXIIPxfMfobYKA3L0zE/qQYYndwYd4MfTsy6y9zD9weXAI3Mf6rbR8jWBWb5k43LTQKA5kR9/Fc/8X7AlRGF1XwHs3VkJ8Xl5GefCSlY46bESS6p7biclYCkEec3skKmzpu7Q6On7g7YzZR1trRu4ufaYNejxQrw2yT2XsFDVASjZK8cKMcziBHx0AeKXnba
    oidc.authentik.clientSecret: AgAnnrhb/jo14at8B/3LWG4t1k5pEpcT0lVsUa0EkbxFqftfMeSjDfpCFKcHUFFZf+byOtpjpTU7Rw1dslAtiXpleC92Rf6uk5HY8Gql5bNUmHxdjx+GXmOjb/j1g3uwqqrTUrIpf+iRS45XGIKqxWLtFcYs74i8HHE5nUcJRirXDXrtZ0AXqmlPBZI7dAPqxdmjI/yhEekQ+nDtnHjunLUOmCq/w5UYgpLMHIoDqCASlRltqxwqTiPcAUBIMO+Nb37dhrgTBWvIZ8JTtv0zu5qzGgyEIJQgr3tZOV8XHFxM6iuSyhr4/Sa1PejOfqAbcP6utmjInFLYdWwkC/kL/PVZSJLvnbmrK1TQQJ9hxShni6kLnIKNqVdvjQQYA2/wpWWSahGZoxnihduBgl+jDD+ZLk8Sex5PGhMFHkZqHETAAQ58xMfZy1HuLjFsYaAWoTDqkGcwIaLxVD4jXqWMLrF2zQQcrR3ZYQ0LsixbvGD1HO5A7bo7HHJQU9yMDNrKgwp1x1RQeuMyJrwFE4hlD6mwPplXRarjy13F0guchnCdhog5IDEniOGFiwkiWS0rCKOaIHmh935G8Tuf2pOXpsajvvzW2jTlwxHokJ2TnIGWYs+CO7S9fACYxE4WQBirbMfj59rjmXAXj7LKAX/is7+1NV4rS0tn7dtFHF/gHjjgsGW19RqRJrH3M3U+s9gzwEhC98moXb0uv2fSCz8vmCrjEAdyBz1XFOTgmMjkayHlT0SOEoa7nmcVarhyBssD2kuKJagHG1Y5n/CoHjbfm3b77GNEHR1W6lOMCPK7DTDPSdvgeyjmXlIScD+bk+fpcKBjHrU+H7MsYKFDU6NrXK3OnC/8dUAhgppsE47BpglQKg==
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
    type: Opaque
