---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/patch: "true"
spec:
  encryptedData:
    oidc.authentik.clientID: AgAttLoOa2G139uGmsDS3DUp0hHMLbQGs6Vl792nlCMocMwfy9MGzvUi/dH/H42V2ZRpbt2BEPVvqspcZwVTLgwuaLgQOzcZcVJFp+XSVpKzBz13BOMp8EMVPhB2PPLlvSQdCQms6QKJEBn08jGX395BjWyXAUJ1R7Tue40KSdExz6RJuk6Ynm2TISa7mtJ8wGfxTQpBnUkehdiRQ7Q6nKkPhdpgVZsEzXd2k2Kyr/X0/VkvBLW/avZKVdrsMsyANZRsNi0LbXwFjr5JudQFT4FTBodMNz1zKaGQlbFivoJuWNR5tYE3Vkp+eQHBrKGUX9ZmveIImd1n1cOzpVV73Lqz6aDutllJd/F738kFkzBCtoiIbogtQwtqeiubUMuXjbQqNrB8PasW+kWT5AmFO6nMqUvv/Bb276M8KsUfaG82HusJS1P8Hcxb2rNWeHQxlRmqPNI2MhTrX+fsmm8i1F1iqJjmupakOlK2h/s98l2qQbeGP5kuciI7lN3q2z67qRPYG3AfL5zFP+ka09YWoOuwHPI4t7J/aZA1L8j3VGqUlB9j/AuDW0gKy8q39O6Dj4gkJ2/6ODhubwnRQMG66TcZ6ANoPY1V54ABOSGjA3LWeK9QaGQRjIgjCJF/jhmlL0p9LRa+aL061fOsXnRfs1Jdn6AVIE4VuyDXJ6Y45iDYmZaGnfOpCGzmEehNYPBzE2KOhutqfE5UFnaCQ2R3/cmDtmD2LAAR+DWIDK0mgXvWj09XUtRSjcK25w==
    oidc.authentik.clientSecret: AgAwhLauIi95WYor/WyUCWraJlwNdRrKLG04XhoCrXlX6CO+8/FJMQnA2tDwMGpAIoOULSageuBAWBphZ2bmmn+5wUBv98Ldio/R1E195wGpBNOO3sbtn1uveU7Dgcku/7RrEOD1QVUzgmkPsVto5UneNkHVeIfvVidzc/GxIj6Dn4qwRRVBtwiZ0Niy266V6GAO9wT8QROs/b3+RsC14dPkC+GaKv8e3sGIJur/6OievCvrSSogLfnvAPQ05UTiLboq3TW+itnlYGUBfdSkvwnCF4LRkfdpgjiruqrHLmy78FUheuCDxwlwQvthXrHOua0KtdTeoSX9bGxFsw4Nv78nngnFeChLlu2Ib0mqrzjvlRdekEURNzlKu0SFrnekHjww+yHew3bu5SB0FS6K6vvjd1LgfGP/zfmSVljTpMs4O9kjtsPuqRJ5DN2hVhO5RmnNYXny6H+bFWdmWo8Y+R3U1E2h4RljmDsOaoTWIRnVLahfAZDU1oR+JGYsQChiA9tk4Wk2u9I/pKdiJqGrpy2WFNp7SYzH7QvZg+iP/1Sl3Hk9jxHSgaeoRxR+vpkzPYrGtHZ1+MBYGEjCsBvPqY7Od4JkdR1U3Q5b5dBfHQqkEX3iz88U5TpXsnIxKqsbnOE3MPMDjyyCuZFweO++ODBuZi9iTDgPmt4Lk6DMk55E5hpqCh3co8TadiSOawcKTC7NxK58Osy+2HRPqAcH0XRou5X0r3u07cXkI77NwmSG5GYzxw4QqNvt4sxL1j5A7ugfxnFjHJz9vLaWnSz4TlMW+ZspTlMIDRu3IZgGUGlOfFvM/Rc0PMcrpbklrM/06VBJmkie5t2qGBDXdON/yoqP6p7CFs6qwh92GcdRUmegKSI=
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
    type: Opaque
