---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/patch: "true"
spec:
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
    encryptedData:
      oidc.authentik.clientID: AgAy+AGW2hXup0yz6V/DJ5VooMWyJFtlcTdLetLWuqPRTlyxzdKKOHvU9mO5RRbbJgkSXiFxUXUEn9Ip1pb0uwvkddI6HwfrTSWrmVohqkVG9HtpKDFnmR7lfKFqeyy2/lJerAhcvhmmWuZPrFFxN6+7So6K4jhocGlpGk68zs0y9eoXI/kuiyKCl9g8r5YPg82Td3+VVHfBEyWEiAFc1TGqWodkEqKXM/Lbtrss1+6NlSDLJD40IbCzRHKdaI4pZi+vi7mlgDEx5zHZSAZTUTaIpQRebjW/kuWjeGNuax9V3Y18vEbjsiGMiHSmZS3k9xIcI/1PcNhXY1vPAusF0K0aq+KjuPni0sDKo9UJQscyKVeqKxl2IJS4xuF92r2sv044snaeSWjzHc1rr+P+xA/+m7akXx79Ao33q/CAEgQKjgCfMl8+wWMt2Bxi2m4c2F9EgTvI7ByCAZ2fdz2Pr0tyDlg8Ur/Dz2kIYKaePpDOguayKgM4nyEfKkWWsjcnUVyWHFvkPhnyxskU8WNkHz31DuUYY/AzabYsjLEJLDC/9FFFoOmUBUxQc9CtbUwkuLjA1YWgn9vaACC6VqdRus462JGA32eGs4PWkXVhbyBNTqyyAfrSJegqc+2tFhfic59j0Z7lgHaccnyccTDOj+fkpho/mEXVi0ayViJo5EkeO0sd5RhM8wGhcpy+qjo8z+C02d9ZtG/3uYlZB/PQmzpWbAHl3A2C6TZ3pAXuvvJ4ydxjIfKbmcIf
      oidc.authentik.clientSecret: AgARFvWJXY37C3Yshs3zMemrXocu4KxaSy9LjKyJnMjTaJyMefuyLSv2BkjBiEyzVs23hC0DiwcaJtyCMZJ1NmI/47nHZnClntzIwoBjp/Vt493ZHd4RG0PJSvua+oXp8xI/rJGoFuln184XL7W1TIT6y3E806p+fqkBpnwPo6LJAag5lo+mQ/+lsRYqbhrw5mu88qqUIYyL2TQemqd753palBgRSkraD3myEMHXcPuy/9t7WxYgqevnEx0EXkTuIwCgjW1raWCUZFSmzzCjF9TsL9XIyqNzUMz8bOCMLrGTZJORPSV+KX7K0GWFcwbja4GG9xsxe2Yagh/wc8Lt5HNpwvYnLk7/vvr2Ah0XWA5+QVu0/swK7JtqUjfmi4CvLD1BqZT6beH9ON9bYEe3GbmjEygMpxtSQsdTEDVSnHENeKZhNeApONXDDuXRfPd4ViP7C/S3hmHG9M9zxX4xHdeUd/yKj1UxDdN2wEmViSHk5PWsB4lBVya7UIsg6CIOBNZVUafvMpTFt3J2Q+cAm3QAzidWEI0rw59m/WhP++TV1llnSSTs2SlUZu6PWBaeIHHhULRQqo4Sh+gBQXQ98fVJlnIbOT7S/Dg1DKDqSM0Ly9Y/4ZliY9BdlFJkikSxhqcxXKTZ027+NFs44t5Kh9oA1UbI4rwqy6xqR/Fhe3hG0HeqbDPP/5Vi49ICHINlTMfOXTaKFJCJoSsAQAwtu4RYyVg2WhSfIcuexOZ5AewdTYEKkiQzzQlowrgOW3W13OSnQ5PYvmKWLtlbj+seXdaHC46xWMuk8pd7GdfkejkhGYAazZoFa4TsqNmUwCy35HCaLV2thx+UQdXCqCn95F05VgCUbU34QW5oQ9F+Yl+DBA==
    type: Opaque
