---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    discord-webhook-url: AgCf+Z+ZLwN3d/yK5yGr2bO9n/VvIPHpHU84n8ipAwONWVgehqSvjsENyeF5hXIQ3Jxf2iMXhsHz24izCgPBHO4kn7Hg0Ki0AP65zSC4EZua1yy/yIZWoahXVP3lcLsCioZIkDjp+POum3ChA35AXy3HNSRMVhRZp9V/Z155QjIsQgnW0IPx45ZVo/1vaGnwGxxDzC0vff3ImeeJxW3H8TnO1MRMDKwHXdeCtDVQSqaS21gCbL5u9lfdosahbAZ4nUvidB0/NZym+uKc5zW0XA5Y51KqpwIuhFawjEII4Qf7Xu3iPz27uMfqN//4kRWeFm7LOHORu9dT3uYJzuyh9FmRw/HgicaYAkaQGr8idq9qJnFOX/5eKwdgfOxC/o9Xc6XYQbFWAwvPRX5AkJdLZ/9lOL4LiSUuGBTMm0+YmqXSh7UWye+01OgsOVgqncWI+dOl9sdOK9qIKBWESd5LVLBfLccCGOjxnJUlwHq5ZBsMj/mw90zdAdUEXHgsG+HiH7bU4yPk6D/ljawHMzY/Dc9wuzgIbptIA7c7g4HsaDu0GjYMDR6JpNd/8NU/GQA9V8CE5TJTg8KFrKpNgDhtiq4CPKV62YwVkB55OX7wUnbor8BPOj/9TjhNpXOLN21rllSonUKtdK6fIu4UD2xhhgPyLPTu+AKEDixC8Av3JtPeSj2HT6ZfJZsHGTyF8xn3OLFr6u+55tb0HkRcxPYr6DpHTmC/yM1UjHKvPfC7i+8LWwgcG8amNeekVPFdAuxWOXB1Q4074g43usmo5PrE/AByyuu/mZ7Yy4yIP3iX6MGdJ79BqS8QVW/hvJKJqgkxQoqGzgEK5qwxGtaACfQgi9BXDxQI/UGrc/1a
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
