---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/patch: "true"
spec:
  encryptedData:
    oidc.authentik.clientID: AgAJw/99OR+PGWB6RJukxskZUWSlwEaszqiu47slPgnPMzz2ZSoN7fS1Xw/HO2U/enIgMuCJaD8pRtL//86NWKunErhe2R5/ABxMOkFGFuoNc4S4xKj3+n4Ry7p98UUpQ03ays5vcjbW5kKl7knb/5HY/bHcC2ibCHI4zOCvG+E8yHpMgqVZn2lm7tJquM/O/ioqs1L0sSSpNtxydF9Q8Wn2skY5Rldmc2WU6ZmCPU7Vjg3lLqYq4e0ky8ksJo8DmFsMOcaPyuPlk25BVvsVYDqXQLT6qNCno2NTlJFZ5a0DLmeN6sqUqb3lhqJVwsh8jNrwieJCjRbt/uaimBZcnsnutrKet2nvP11YDA5AQ0DYZ2GHEQme4VaVT6YH0aHXQT5OWWwnbu65LW3SiICDW30ypwzDkOnpRE5JPl6CGnWaDkc+Vd+qBFg44z++x4G2JNoV1woW6LnjsFIDAulPLRC7ob3/WEkW/uYO8HJYaACFS/+dCykqdKz4rDrRKxET0WSFaNvxEOSv07LcGzPRSqoOSuJyHraDNvt7xZDySKJ1J1A8Ax84mQv5DgNWLPhtjUzcB8+taTm4bCWqYQP1s6aMrULhAVpB4Ul/lGL7fi+yKb5yhwrBL/CqC4b9BQZA5Kd8wIrtcd7KtcKbn4YX7NiRbpz4JdbCEEv4GbWluJwtkZEZmy3ICiAAhYFq7YMC7vRKfVitt9X5MGYzMjRLntDQNgPqKFJUJAeed+o7d/GE73JNEqEnqJ9w
    oidc.authentik.clientSecret: AgAYNEMPm00eB2TSUjV9eciBTJ+gP17vYnrQ98Gg+qwnZga0Ns7xT9jbccWh0Sw4IDp3or746lNaK/j8ZdCQX4/ybWE0pK5PQ/KXtytD6q/DFciQoupw3QAFA7PxC7m1dhEDsLeI/VabVR6D3Kz43KrgPMZTSwKifJHmuXzYBu3BB0Jm9hMw0QPdjAN9FpN2ZKZga2xcWgR2ckeYEjJdD49mVYIP+931b93x6V6+1o9u6p4ON9XESUzWfuN+7vuimvDdqUVPzGLHbFQb4XdK2NHTs5lqmjrSasitPzu4TpYu/67jMllQaeI4pHJ5uXYrsV3PnQmuBuvCsZ4P7NHu0uSaL1hbid72dqY9pg5Wfym3UoQPMK6sajgrplJzOJp/FtCFvi0tUX1lyJB9eI5nqo4ALKZ1Z7mx+yDYMno4te9I2+17Kd9hWtuj8TLjFhX6jRQVsmPxIPm3HcK5Dn6dQT6WKl+/aLmkyYkoFCzs9awCXFsp1U7r6uneiXWelPChnoxOCfuGheQWu5cw30SZskVMg/vmOdgxJYrXVNgPj5PWdSNeZRB7yCdWF8U4E1t9S2/w41dxvgOBC+DmT/wtleQeYYABqGWlcDLGZzXTA+7IgUXBCgRJJJ1GARUVnISRKjwvr9vcMeqTkvbDFwOBuGwilPxmATxhEiD0JsuD1naC/FDVzXP4tgO/e8jophFvHQoOsOrHsBPtLP4I3c3vfKQDWgyTFIkZcw9wjbRHiqk0HV5xVIgUNiFMYYzETv/b/kBtt2WJV91epP36UqXKt7cDhU1+Wrm5OuQdUjvAf9XyzA0+YxZEfVDXHIaVoKfTSGSPU6oCInt4+giZo02BqjrZsqvoDEeUm/gwBY/LwxyvkA==
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
    type: Opaque
