---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/patch: "true"
spec:
  encryptedData:
    oidc.authentik.clientID: AgCJTRkfxrDqbCY3aeYB8XrRpiu8m4flNz1sqqZLiFT0eb46KPzXsavcOefLkNIgWR6GSIX07698hfoBEz1UZPE7BOjblodDtmN++sVIe5hmCqwASSjgyJqNFH05wuEd7wgvoKXwzg3NCtg/ldx+Ctgk+eLGpTp9TCHjFIKbB5x3FAazm6ZQoRU8KV7HNG0xH1As/yM56txeb65MiqFMumqs1ogHBMMZDUyNblyc7e9AacvYpKBjMRCIctVE5C7YArj2YMZwMF1MA/RlaK34bzU2Vuz5pj9WeTRc+otlLUG4KEBSd3JsjDZINFNFoWyg6FTiDzhGGRPUDiSRzl+shxDtWEwEMLcgpZO2LxCYtrJncTWjfBFqkhvBOdjjVG047+HjFJYFVMiMm+ov1mry95wI+5JHKLWIjxTqrUBsVzWqQQlb/KIaLIjMTfCPrvxlEdEaOWS3tVJV5X2SDjt6j9rxvXELK7ougUzS1NpBIw6/fhr9nBDUQp2SiChF8ocG9SVRyeXdpr+8Mc+NhAuUi4GADzMptVUlt6+vFsWi0ZlrBUAfOxOHrWJmX/475wZSfBpUyhepFWmuYfdQpuQthy/3F+x5YicDswHeKpMH3Fyu5+zh88YyZ4zWc8X/p9PIESkXmfNU+J5PtOELmmI3LcGn75JDSXBfEWauCsNv56B02CaKs0UFIDt0NeTpwPajfTcHFteQZDyRJfVBL+kIYVxcau1nAXlYazjAzwkMx1w4xsAR7ZwpNFsFXg==
    oidc.authentik.clientSecret: AgCjS/8OOeVKeQlFi+LAL/iQUT6uTg8Sjf9ASC7s+YpCxpc1y91UbYUOTxQ9NLM3cXZ/mtQ+abdNU/jFRRNEMpEnAHpNZ7Z4O9YnaCVWFuE/gnLwL4ks942FY2vt7w0xDuuTk9OMDqMmWGGUlRy48VKK2fMDibvXswUnW5DAvqNmqvPixbZ7iI+TX6KVwiA5rKjwZ8R6arkkCGD92rQ29tAwcjU4y4q80YBVLOK3cuKPNTAmTWyQQUktnM90ZIWYAG5MS181tlhzWAhCezyJD9hF3enCUl8etOYNGrdNrruzQJ8/aw9eTbjzbDpVNbW1GaH/ETz16VmkfPiPkfxRn6jMAKWTuCir4ojidL8Ydpb+fJGN5Ieby2J5DTHTrlSQrKH6dLoOODi4StV7Paq2sJPGQzjKkGjnqpiEdc4r3SZn4AitsdpzV6+XYqpqLOYM+osWwisYLjwYV3UEpVg3D1h1S3mqVY/Z1Zgp0LQD7DtBiWfcvaRy/fHed4QzO72P3aMSa3QKF0Hv6Bg7kBAsXi7NlxzvNLnN+kXriL/nERg0gbg/m1JvOfqpvYybCDacF2EaYPS4EPV7cLEQr7BVtCaV636DCkC4/lRRFntHN8+k023nhBaUiyIyVjvgtuWQeoj76dQFa2lvmES4rEAC8TMOzFarV4S8gdemr2BfWErsh9WtECZcR6AhWd+7lvkUptVeKDykDHKaVGHmsUX+YdU72mjKjj/slgRwFNeM6HFw+sMh/mWoFBtGSpaf0/CCUc8lUPSXDzPj5WT7hQ7Jk/DKqnQiDO98BcCnSuBazvdDRSfkbIApgSYf7cKufQFSyojszndYfQTzMuwpGFuMALja62G1hCe795+Fqu6SFLLf/RE=
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
    type: Opaque
