---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/patch: "true"
spec:
  encryptedData:
    oidc.authentik.clientID: AgBfqTwAraZz8hz9/Cr0JdqflRtMF012pdLnupYiQscM/1ckk+DiGKD/HihkMPobFGqEToNFlkxNb7WIDM/p2/kUQ8XGInshjJTGW0xhUpxsPkA+7IrzS2LEJn00FtuIPVD0eOUpHDsu/3hKGnx2/5rFa/FC2kT3/nX8uUqk/fBUhGpeItyWwnrVuFEWYa539IsqBaDmSorWJJ5a2WU3MQhxFMQWR/bfZe6fMcVKbUBjq7J2/G5NaoMwL2LB2Rc9cbY5zQ7jxDc4deeyflXu4M5HlcyQ17iUmTFx/JoMYfjJsWEdXF1CaEGVHo6aIOTmOxRk3sHIBNXQ0ZcUDSnXoGOGf7Iny5fHhKjPVeKu5NiVVGLHlj5pnQlWxzaw98YZh2L47nD8HfLk++YBKQ3Lr0TgnfcJIOqpFCIOOtqbOMqhU4Z6fF3u1suBBPr6TUNF26EsJPj5S2gYyEV2mXu8nxiA8XxHPCqiLiQmnce+lpSrCkTLb3DJT88iXafRXo0QFNik6YTLhZA7laruwb3dP5S8BxgbXK1F30Sh9+HyseKAPLUdaGrkYIgmO+VGQF26D6ZfDfzlezu+FpO2MiFIOnGDyRRXKfNqOV+MXXmPDF6ReRxL4jrsd7cfGHwL2U4Oj7ioBXj28ybwFo1/5gl6sBaD7whL1Gujxw/mEtXaNtAi484LxbS0RnJKwsrgqg+6fVZSvQNU9kJ7kf17C00HPe/AL2opGI7FtnG/nCXkVO54EL0YXVL32PY+
    oidc.authentik.clientSecret: AgAE2HmohkmcPa4FmqD8SDemfiQp/IV8ORWSQR61BWav8tiCXeMpz0AzB10VudrRYU+2h0qPL19kis0gpw1TILzx5WPvU6tlh7AJq6ebFMIDR+tSggKhTQY4uoFwPAkBe9aeIgbTQWVQuhdUuPZPIv6cnyeCm08+tD7iEN5zjCEmJ7o5ODYgSz3GReXwJokIhnEDw1yK8ghzwpB+5quwR3nHiBlROdiDzfCY+xJ7pGaoFIsUuw8o5X6LrEH6MQcpvzlV1imiAl8lLR4XRDzEKW3Rsv1SuQdl3lZ0VPrBawjLm0Yrla7beDhOnhGk3eqLhrczM4HZGC8kZtKct8CisYzyK1sU3FRyHBgsBSbUVllWTYXUcPOE1+nBfXneoabRemid846+ecj3rxPaeQLFjC5+cGaVF2RZKE+SZyZ/RPnPS+w9P2CA8eK/+cAirR86PwcuZ/4d8bdx1kum13o1jDWH7x38ZPgfonkDEv457LSDfHgFEBeyhkFQXo134q/0Kh3oHIVAGzap0rJnXX7TvvPxhwfWtnW75TwW36EpTRlvaaBsMwvUqDQA99wbQoWZXyQ1x9IguTGes1iEb0ty49Z702z+v8vdZlPNJIEet7hiNytmB90FJF5QEQxRQD8SUa83hfRCqC5++4EWIaV0dIH6/5LSz6oYGyDyKcKXxYDLzvN0UpV4kc9vEicLox+QTAzVOBdm1KFe0MolvOy9QwBvQGdw6Oz50WhNOJuRrKhN3VKDhd0aPmxIlKoku7iGEeaNtZA/71D5oNKfQsLITewV8OcsYPBq9mBlz95zvZ8HA1rwxWdAFDitFbwE0hKdjmjAymBXCJ/9bq0UWdnPPcF74a1jTtj7DJMaKXfXBbkNSg==
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
    type: Opaque
