---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/patch: "true"
spec:
  encryptedData:
    oidc.authentik.clientID: AgCWC+6c9arjxip1sXac0a1eKsglVmdSETt/krmu1CRXJd/akmj651tiUKVgE9UsOtWfELFrTgZgx4hJGiNluhIqhkzXOaLsXhIngHnug7hjwWxlF9CSpBlN0dkHhIWAtH9vFamDX7WReXUHGqbi+99I30AunoZn11YIlyYDN8daRg6Sg1NFPQ7q+svOHO+hsx91uJV1nPugECpIYtD5KsLY1nKKsTtkQC3sE6huw2pXPEan5PMpDXcnVeCT6mwBgYadvs4Fm/tMsMubfth5vRsmakD1cxRVbT8rr42+d7bkmRqsV6jqdN6PPIYO90Pqbieg56aiakVIVx656cNLgm7f67Gd7K9y8cyysDdLyiC2dPNqh7wxBDix/b3bmtKZGPI2jV5PKsrNfQO7gHUk3CQnU4S3/BwRLnO8BJRwX5en1azqXl1W+zwrbweYycxVl6fCxuUyGSCZmdr/VBzG+ExmmvNSF5b340js9reE7LTGHNFZ0FrUW/PPpyazxcfCo5ZXWbaOd1jlekHUY/eaMUj+ZVeUmHn+uS61aLQjbTTlFF0/932yZuOASa0JeBp4Tw606xPAUOac01xNn4nSePOatNj+1GPwuguwvNtcQVj+iIPLHKsPxn509MTWpS664o6jKDu2PEx5T6ZDGhLgu0+NV3PoMAq5lEnxlVfkR81lT1UAPzFA5HXv05fV98D7dEYh7is9iwWc4nCKT4UYLR9p1ZQzlwDWS5Kr7G13S7EgZf/Sr4xbQxF6
    oidc.authentik.clientSecret: AgCZ1zotDP4FyL2WgQBzBJx2KfVENTepLGG3RJ06gPxOky8170hV1Mp6HcyvmEKq6nx2aYNmKiTUchYd9XkqMOsgVwn+wdNny2iNTOAMzmVQt5rP8NOaNiLIAwFl7vyMWMtsEZU8bkmOneFiy82OhQbAXbNS0bBFlsD8mxBK+yS1gNTul14I66CtnJYPyZn/GBNvNa+HiBk1a6KKQC/9sm+O657eJEWNQ1pPuflKrmX48gdglz9h3M6g3Z4r+WBcilazxBQdTQUbH3owUtkAHJCsjiiCLBSxSIPH8iFrVR1GOyhzXe0Yv8/M8kcOipkkhTnVTU8RGs+DfH9hj0tD99y30ly9u6kZ3rRj5z88hKU3iDNys/vUeOX3osdqltvvng6coZYhEY2gNu7U7y6z1PF8xET+qaJB3pA70IpCAx2sxRFDpshya+qWr7zy+bKTUJsemsWqGzmOlMUeqhHD3Ms4bt8pT2b2Bl2E6a2bq+sgCOENnC48vGJ+/sbhgIWuHQMivbkS2Gifg+FyCElDo1k8qRxJ+OLmAgrdHgBzfB349A7+iHYpLMuFI5SmqLeUYULNA3WxIKowDz4MP3jo3icoB2C+Po9GqsACjHu/hJ/bC1Ws8kOV3PkUpQ5+wFhrD0OrjAK/VEhThCSpTkflCeO8e0xB8MILxB+URG3+ogvZB9Zy0rBGLk/9HOeAqlEmUs2rQxrJ4Zx8z/Lb+iNdcTaqOCs29us/DpV/POrBh9BKSnVKRnc0HZhXV9WrOihCvkA+WBEZQqHZOHSSmMrwoH2/fuMHQdBXOECk1wZNi7ofEetvFhSpKNQmCmpZNfR1m0qNx07Mg2FQsCG2Awn5SV93S2BJeAkKCpg53oHp9CKS2g==
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
    type: Opaque
