---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    discord-webhook-url: AgAudNnk2gfJRDhh/ZSfnsEA1absnrpBNgiLWhhfqGHzk6+4EZ2eAtV0NpvVodbr++O2W7sWPp7D9omreWA2nAfl6ysxb5QnAsNxu2z6FhKQfyePK8gXhc3MykAlXVRmpeQEfJE6bLKhD03XD/eqjKXRES1Cl2AXOF5kmE7tMR2WPHqz6N+GaoDNeo8DXzec86kpa3il6MWp+kRtWOoyOIwYhS4Ushmswt2tCb61obMADAaMxG82MD49Zr0CZvH0GMJgO9TBcBu+39YN5PR+iUi1k1KIxrOpn0oJ1aB5wDqd0sNj2ln1Dno8/cg4/JCgXvVu/OI6LN1547naqJjKXL1lztA275YIFwVYbJtREl30XYU8MTPQiZ2BoCjcau4UH3Y8nx+rSfc2nsRhBo1u3pD1E9Nx54jivbPMdQOKGnprSbMUBHKcdE9kc7vQkNE++RNEuuC+STQ9Nj4Xl3xQbWTKJ4SspUxT8/SgUZVvTorF5EnMCSKRiFpDsVZKK8pDIllvfu3fE2EHfvCr+vh/ZM63TW3kCEXwVB7LJEcosQMOQkgi9Bi5t/kAVTILyKXMWCNki7LLgGcF7u0cRvenJwuXPXabuqvvCpRDhg36XrTl3OgoX+fiGjVG6Fh691L0GOwIw/Ar7/P50PMW3odUkStb1bYSL76kCVTqjPv/ZJNLH9rcc+uz/aGWbmvNEtzbUEfXwk3K1EtosdvPfgEMvJPlMkULnCNgVLnNkSbsfsGI8wIt4nCTcQJpSXLaQppYPyVSph1Bd3P6qFf3TRZJrOMwzdEGLwXOUEycQ6nCyXlyy5qptuNOfuQ1TPAwiPmhnQNYvLNCZvHmR7INOjxEzPNaoV24+4CTfVrz
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
