apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: db
  labels:
    app: mariadb
spec:
  serviceName: mariadb
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      nodeSelector:
        kubernetes.io/hperf: "true"
      terminationGracePeriodSeconds: 10
      containers:
        - name: mariadb
          image: mariadb:12.3.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 256Mi
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-cred
                  key: password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-cred
                  key: username
            - name: MARIADB_AUTO_UPGRADE
              value: "1"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-cred
                  key: password
          livenessProbe:
            exec:
              command: ["sh", "-c", "mariadb-admin ping -u root -p${MYSQL_ROOT_PASSWORD} --protocol=socket"]
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ["sh", "-c", "mariadb-admin ping -u root -p${MYSQL_ROOT_PASSWORD} --protocol=socket"]
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
        - name: mysqld-exporter
          image: prom/mysqld-exporter:v0.19.0
          ports:
            - containerPort: 9104
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-cred
                  key: password
            - name: DATA_SOURCE_NAME
              value: "root:$(MYSQL_ROOT_PASSWORD)@(localhost:3306)/"
      volumes:
        - name: mariadb-data
          hostPath:
            path: /mnt/cephfs/docker/db/mariadb/data
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: db
  labels:
    app: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
    - name: metrics
      port: 9104
      targetPort: 9104
  type: ClusterIP
