apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-config
  namespace: harbor
data:
  valkey.conf: |
    # Valkey configuration settings
    maxmemory 128mb
    maxmemory-policy allkeys-lru
    # Add other necessary configurations
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
  namespace: harbor
  labels:
    app: valkey
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: valkey
          image: valkey/valkey:9.0-alpine
          imagePullPolicy: Always
          command: ["valkey-server", "/valkey.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: valkey-conf
              mountPath: /valkey.conf
              subPath: valkey.conf
            - name: valkey-data
              mountPath: /data
          resources:
            requests:
              memory: 32Mi
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
      volumes:
        - name: valkey-conf
          configMap:
            name: valkey-config
        - name: valkey-data
          hostPath:
            path: /mnt/cephfs/docker/harbor/valkey
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: harbor
  labels:
    app: valkey
spec:
  selector:
    app: valkey
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: harbor
  labels:
    app: postgres
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: pgautoupgrade/pgautoupgrade:latest@sha256:b851ed7d896f183616753c65b6c4a159f8bc8aa14a26a11401b69cfb93b952f7
        imagePullPolicy: Always
        resources:
          requests:
            memory: 128Mi
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: harbor-cred
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: harbor-cred
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: registry
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-d", "registry", "-U", "postgres"]
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 60
        livenessProbe:
          exec:
            command: ["pg_isready", "-d", "registry", "-U", "postgres"]
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 60
      volumes:
      - name: postgres-data
        hostPath:
          path: /mnt/cephfs/docker/harbor/postgres/data
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: harbor
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP