apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: harbor
data:
  config.yml: |
    version: 0.1
    log:
      level: info
      fields:
        service: registry
    storage:
      cache:
        layerinfo: redis
      filesystem:
        rootdirectory: /storage
      maintenance:
        uploadpurging:
          enabled: true
          age: 168h
          interval: 24h
          dryrun: false
      delete:
        enabled: true
    redis:
      addr: valkey:6379
      readtimeout: 60s
      writetimeout: 60s
      dialtimeout: 60s
      password: 
      db: 1
      pool:
        maxidle: 100
        maxactive: 500
        idletimeout: 60s
    http:
      addr: :5000
      secret: placeholder
      debug:
        addr: localhost:5001
    auth:
      htpasswd:
        realm: harbor-registry-basic-realm
        path: /etc/registry/passwd
    validation:
      disabled: true
    compatibility:
      schema1:
        enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registryctl-config
  namespace: harbor
data:
  config.yml: |
    protocol: "http"
    port: 8080
    log_level: "INFO"
    registry_config: "/etc/registry/config.yml"

    #https_config:
    #  cert: "server.crt"
    #  key: "server.key"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: harbor
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: registry
        image: goharbor/registry-photon:v2.13.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 32Mi
        env:
        - name: REGISTRY_HTTP_SECRET
          valueFrom:
            secretKeyRef:
              name: harbor-cred
              key: REGISTRY_HTTP_SECRET
        volumeMounts:
        - name: registry-config-yml
          mountPath: /etc/registry/config.yml
          subPath: config.yml
        - name: registry-config
          mountPath: /etc/registry
        - name: registry-data
          mountPath: /storage
      volumes:
      - name: registry-config-yml
        configMap:
          name: registry-config
      - name: registry-config
        hostPath:
          path: /mnt/cephfs/docker/harbor/registry
          type: Directory
      - name: registry-data
        hostPath:
          path: /mnt/cephfs/docker/harbor/data/registry
          type: Directory

---
# Registry Controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registryctl
  namespace: harbor
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: registryctl
  template:
    metadata:
      labels:
        app: registryctl
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: registryctl
        image: goharbor/harbor-registryctl:v2.13.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 32Mi
        env:
        - name: REGISTRY_HTTP_SECRET
          valueFrom:
            secretKeyRef:
              name: harbor-cred
              key: REGISTRY_HTTP_SECRET
        - name: JOBSERVICE_SECRET
          valueFrom:
            secretKeyRef:
              name: harbor-cred
              key: JOBSERVICE_SECRET
        - name: CORE_SECRET
          valueFrom:
            secretKeyRef:
              name: harbor-cred
              key: CORE_SECRET
        volumeMounts:
        - name: registry-config-yml
          mountPath: /etc/registry/config.yml
          subPath: config.yml
        - name: registry-config
          mountPath: /etc/registry
        - name: registryctl-config
          mountPath: /etc/registryctl/config.yml
          subPath: config.yml
        - name: registry-data
          mountPath: /storage
      volumes:
      - name: registry-config-yml
        configMap:
          name: registry-config
      - name: registry-config
        hostPath:
          path: /mnt/cephfs/docker/harbor/registry
          type: Directory
      - name: registryctl-config
        configMap:
          name: registryctl-config
      - name: registry-data
        hostPath:
          path: /mnt/cephfs/docker/harbor/data/registry
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: harbor
  labels:
    app: registry
spec:
  selector:
    app: registry
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: registryctl
  namespace: harbor
  labels:
    app: registryctl
spec:
  selector:
    app: registryctl
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
