{
 "title": "Server Health: Metrics & Logs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_ds", "label": "prom-ds", "query": "prometheus" },
   { "name": "loki_ds", "label": "loki-ds", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values({job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pressure",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "I/O"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"$node\",job=\"$job\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"$job\", instance=\"$node\",mountpoint=\"/rootfs\"} * 100) / node_filesystem_size_bytes{job=\"$job\", instance=\"$node\", mountpoint=\"/rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "gauge",
   "description": "CPU Temperature",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\r\n  node_hwmon_temp_celsius{instance=\"$node\", job=\"$job\", chip=~\"platform_coretemp_.*\"} > 0\r\n) by (instance, job)\r\nor\r\nmax(\r\n  node_hwmon_temp_celsius{instance=\"$node\", job=\"$job\"} > 0\r\n) by (instance, job)"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Journal by Level",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\r\n  count_over_time(\r\n    {job=\"server-journal\", instance=\"$node\"} \r\n      | logfmt\r\n      | __error__=\"\"\r\n      | detected_level = \"info\" [$__range]\r\n  )\r\n)",
     "legendFormat": "Info"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\r\n  count_over_time(\r\n    {job=\"server-journal\", instance=\"$node\"} \r\n      | logfmt\r\n      | __error__=\"\"\r\n      | detected_level = \"unknown\" [$__range]\r\n  )\r\n)",
     "legendFormat": "Unknown"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\r\n  count_over_time(\r\n    {job=\"server-journal\", instance=\"$node\"} \r\n      | logfmt\r\n      | __error__=\"\"\r\n      | detected_level = \"warning\" [$__range]\r\n  )\r\n)",
     "legendFormat": "Warn"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\r\n  count_over_time(\r\n    {job=\"server-journal\", instance=\"$node\"} \r\n      | logfmt\r\n      | __error__=\"\"\r\n      | detected_level = \"error\" [$__range]\r\n  )\r\n)",
     "legendFormat": "Error"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\r\n  count_over_time(\r\n    {job=\"server-journal\", instance=\"$node\"} \r\n      | logfmt\r\n      | __error__=\"\"\r\n      | detected_level = \"debug\" [$__range]\r\n  )\r\n)",
     "legendFormat": "Debug"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\r\n  count_over_time(\r\n    {job=\"server-journal\", instance=\"$node\"} \r\n      | logfmt\r\n      | __error__=\"\"\r\n      | detected_level = \"critical\" [$__range]\r\n  )\r\n)",
     "legendFormat": "Critical"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\r\n  count_over_time(\r\n    {job=\"server-journal\", instance=\"$node\"} \r\n      | logfmt\r\n      | __error__=\"\"\r\n      | detected_level = \"notice\" [$__range]\r\n  )\r\n)",
     "legendFormat": "Notice"
    }
   ]
  },
  {
   "title": "Journal Volume by Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (count_over_time(\r\n  {job=\"server-journal\", instance=\"$node\"}\r\n  | json\r\n  | detected_level != \"\"\r\n[5m]\r\n))",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Recent System Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"server-logs\", instance=\"$node\" }\r\n  | logfmt\r\n  | regexp `\\[(?P<level>[A-Z]+)\\]`\r\n#   | line_format \"{{.kubernetes_pod_name}} ➡️ {{.log}}\""
    }
   ]
  },
  {
   "title": "Recent Journal",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"server-journal\", instance=\"$node\" }\r\n  | logfmt\r\n  | regexp `\\[(?P<level>[A-Z]+)\\]`\r\n#   | line_format \"{{.kubernetes_pod_name}} ➡️ {{.log}}\""
    }
   ]
  }
 ]
}