{
 "title": "Server: Full Observability",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "prom-ds", "query": "prometheus" },
   { "name": "loki", "label": "loki-ds", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"system_node\"},cluster)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(up{cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Node",
   "type": "table",
   "description": "A list of all nodes in the cluster along with their spec. This table helps to get a quick idea about the resources in the cluster.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_uname_info{job=\"system_node\", cluster=~\"$cluster\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"system_node\", cluster=~\"$cluster\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"system_node\",mode='system', cluster=~\"$cluster\"}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{job=\"system_node\", cluster=~\"$cluster\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=\"system_node\",mode=\"idle\", cluster=~\"$cluster\"}[$__rate_interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"system_node\", cluster=~\"$cluster\"} / (node_memory_MemTotal_bytes{job=\"system_node\", cluster=~\"$cluster\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=\"system_node\",fstype=~\"ext.?|xfs\", cluster=~\"$cluster\"}-node_filesystem_free_bytes{job=\"system_node\",fstype=~\"ext.?|xfs\", cluster=~\"$cluster\"}) *100/(node_filesystem_avail_bytes {job=\"system_node\",fstype=~\"ext.?|xfs\", cluster=~\"$cluster\"}+(node_filesystem_size_bytes{job=\"system_node\",fstype=~\"ext.?|xfs\", cluster=~\"$cluster\"}-node_filesystem_free_bytes{job=\"system_node\",fstype=~\"ext.?|xfs\", cluster=~\"$cluster\"})))by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=\"system_node\", cluster=~\"$cluster\"}[$__rate_interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=\"system_node\", cluster=~\"$cluster\"}[$__rate_interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=\"system_node\", cluster=~\"$cluster\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=\"system_node\", cluster=~\"$cluster\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "上传带宽"
    },
    {
     "expr": "((1-(1 - avg(rate(node_cpu_seconds_total{job=\"system_node\",mode=\"idle\", cluster=~\"$cluster\"}[$__rate_interval])) by (instance))^1.3)^(1/3)*0.5 + \r\n(1-(1 - avg(node_memory_MemAvailable_bytes{job=\"system_node\", cluster=~\"$cluster\"} / node_memory_MemTotal_bytes{job=\"system_node\", cluster=~\"$cluster\"})by (instance))^6)^(1/3)*0.3 + \r\n(1 - max(rate(node_disk_io_time_seconds_total{job=\"system_node\", cluster=~\"$cluster\"}[$__rate_interval]))by (instance)^1.1)^(1/2)*0.2)*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_disk_io_time_seconds_total{job=\"system_node\", cluster=~\"$cluster\"}[$__rate_interval])) by (instance) *100",
     "legendFormat": "IOutil使用率"
    },
    {
     "expr": "max (node_filesystem_size_bytes{job=\"system_node\",mountpoint=\"/rootfs\",fstype!=\"rootfs\", cluster=~\"$cluster\"}) by (instance)",
     "legendFormat": "Disk size"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"system_node\", cluster=~\"$cluster\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=\"system_node\", cluster=~\"$cluster\"} / (node_memory_SwapTotal_bytes{job=\"system_node\", cluster=~\"$cluster\"})))* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Journal Volume by Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (count_over_time(\r\n  {job=\"system_journal\", instance=~\"$node\", cluster=\"$cluster\"}\r\n  | detected_level != \"\"\r\n[5m]\r\n))",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Recent System Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"system_logs\", instance=~\"$node\", cluster=\"$cluster\"}\r\n  | logfmt\r\n  | regexp `\\[(?P<level>[A-Z]+)\\]`"
    }
   ]
  },
  {
   "title": "Journal by Level",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\n  count_over_time(\n    {job=\"system_journal\", instance=~\"$node\", cluster=\"$cluster\"} \n      | logfmt\n      | __error__=\"\"\n      | detected_level = \"info\" [$__range]\n  )\n)",
     "legendFormat": "Info"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\n  count_over_time(\n    {job=\"system_journal\", instance=~\"$node\", cluster=\"$cluster\"} \n      | logfmt\n      | __error__=\"\"\n      | detected_level = \"unknown\" [$__range]\n  )\n)",
     "legendFormat": "Unknown"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\n  count_over_time(\n    {job=\"system_journal\", instance=~\"$node\", cluster=\"$cluster\"} \n      | logfmt\n      | __error__=\"\"\n      | detected_level = \"warning\" [$__range]\n  )\n)",
     "legendFormat": "Warning"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\n  count_over_time(\n    {job=\"system_journal\", instance=~\"$node\", cluster=\"$cluster\"} \n      | logfmt\n      | __error__=\"\"\n      | detected_level = \"error\" [$__range]\n  )\n)",
     "legendFormat": "Error"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\n  count_over_time(\n    {job=\"system_journal\", instance=~\"$node\", cluster=\"$cluster\"} \n      | logfmt\n      | __error__=\"\"\n      | detected_level = \"debug\" [$__range]\n  )\n)",
     "legendFormat": "Debug"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\n  count_over_time(\n    {job=\"system_journal\", instance=~\"$node\", cluster=\"$cluster\"} \n      | logfmt\n      | __error__=\"\"\n      | detected_level = \"critical\" [$__range]\n  )\n)",
     "legendFormat": "Critical"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\n  count_over_time(\n    {job=\"system_journal\", instance=~\"$node\", cluster=\"$cluster\"} \n      | logfmt\n      | __error__=\"\"\n      | detected_level = \"notice\" [$__range]\n  )\n)",
     "legendFormat": "Notice"
    }
   ]
  },
  {
   "title": "Recent Journal",
   "type": "logs",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"system_journal\", instance=~\"$node\", cluster=\"$cluster\"}\r\n  | logfmt\r\n  | regexp `\\[(?P<level>[A-Z]+)\\]`"
    }
   ]
  }
 ]
}