apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: ""
    notifications.argoproj.io/subscribe.on-sync-failed.discord: ""
    notifications.argoproj.io/subscribe.on-health-degraded.discord: ""
    notifications.argoproj.io/subscribe.on-sync-running.discord: ""
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.18.1
      helm:
        valueFiles:
          - $local/harbor/values.yaml
    - repoURL: https://github.com/YogaNovvaindra/kube.git
      targetRevision: HEAD
      ref: local
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: harbor-core
      jqPathExpressions:
        - .data
        - .metadata.annotations
        - .metadata.labels
    - group: ""
      kind: Secret
      name: harbor-jobservice
      jqPathExpressions:
        - .data
        - .metadata.annotations
        - .metadata.labels
    - group: ""
      kind: Secret
      name: harbor-registry
      jqPathExpressions:
        - .data
        - .metadata.annotations
        - .metadata.labels
