apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: money
spec:
  destination:
    namespace: money
    server: https://kubernetes.default.svc
  source:
    path: money
    repoURL: https://github.com/YogaNovvaindra/kube.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true