apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer-agent
spec:
  destination:
    namespace: portainer
    server: https://kubernetes.default.svc
  source:
    path: portainer
    repoURL: https://github.com/YogaNovvaindra/kube.git
    targetRevision: HEAD
  sources: []
  project: local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true