apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    path: sealed-secret
    repoURL: https://github.com/YogaNovvaindra/kube.git
    targetRevision: HEAD
  sources: []
  project: local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
