apiVersion: batch/v1
kind: CronJob
metadata:
  name: sealed-secrets-backup
  namespace: kube-system
spec:
  schedule: "30 0 * * *"  # 0:30 AM daily
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default  # Use default SA with RBAC permissions
          containers:
          - name: sealed-secrets-backup
            image: reg.ygnv.my.id/docker/rancher/kubectl:v1.34.1
            command:
            - /bin/sh
            - -c
            - |
              set -eo pipefail
              BACKUP_DIR="/backup"

              PRIVATE_KEY=$(kubectl get secret -n kube-system \
                -l sealedsecrets.bitnami.com/sealed-secrets-key=active \
                -o name)

              kubectl get -n kube-system ${PRIVATE_KEY} -o yaml \
                > ${BACKUP_DIR}/sealed-secrets-key-$(date +%Y%m%d-%H%M%S).yaml

              # Rotate backups - keep last 3
              ls -1t /backup/sealed-secrets-key-*.yaml | tail -n +4 | xargs -r rm -f
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          restartPolicy: Never
          volumes:
          - name: backup-volume
            hostPath:
              path: /mnt/cephfs/docker/sealed-secret
              type: Directory
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealed-secrets-backup
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
