{
 "title": "Kubernetes: Cluster Resource Utilization & Health Dashboard",
 "description": "Comprehensive view of Kubernetes cluster health including real-time CPU, memory, network, and storage utilization across nodes, namespaces, deployments, and pods. Monitors node health metrics, cluster events (Normal/Warning), and historical trends for troubleshooting. Designed for operators to identify resource bottlenecks, analyze workload distribution, and track infrastructure performance.",
 "tags": [
  "kubernetes",
  "prometheus",
  "node exporter",
  "cadvisor",
  "utilization",
  "loki",
  "fluent-bit"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "loki", "label": "loki-ds", "query": "loki" },
   { "name": "prometheus", "label": "prom-ds", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(up{job=\"kube_node\"}, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "description": "The average CPU usage of all the nodes in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 \r\n  - (\r\n      avg by (node) (\r\n        rate(node_cpu_seconds_total{mode=\"idle\", job=\"kube_node\", cluster=~\"$cluster\"}[$__rate_interval])\r\n      ) * 100\r\n    )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "description": "The memory usage in percentage of all nodes in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (node_memory_MemTotal_bytes{job=\"kube_node\", cluster=~\"$cluster\"}) - sum (node_memory_MemAvailable_bytes{job=\"kube_node\", cluster=~\"$cluster\"})) / sum (node_memory_MemTotal_bytes{job=\"kube_node\", cluster=~\"$cluster\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU cores",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", cluster=~\"$cluster\"})",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{id=\"/\", cluster=~\"$cluster\"}[2m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", cluster=~\"$cluster\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Cluster Memory",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", cluster=~\"$cluster\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\", cluster=~\"$cluster\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", cluster=~\"$cluster\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Network Overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{cluster=~\"$cluster\"}[$__rate_interval]))*8",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum (rate(container_network_transmit_bytes_total{cluster=~\"$cluster\"}[$__rate_interval]))*8",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Pods per Node",
   "type": "bargauge",
   "description": "The pod usage in a cluster grouped by Node",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(count(kube_pod_info{cluster=~\"$cluster\"})by (node))",
     "legendFormat": "{{ Number of Pods  }}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "bargauge",
   "description": "Number of Pod and allocatable",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=~\"$cluster\"})",
     "legendFormat": "Pod Usage"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\", cluster=~\"$cluster\"})",
     "legendFormat": "Pod Limit"
    }
   ]
  },
  {
   "title": "Cluster Storage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\", cluster=~\"$cluster\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\", cluster=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cluster Node",
   "type": "table",
   "description": "A list of all nodes in the cluster along with their spec. This table helps to get a quick idea about the resources in the cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_uname_info{job=\"kube_node\", cluster=~\"$cluster\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"kube_node\", cluster=~\"$cluster\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"kube_node\",mode='system', cluster=~\"$cluster\"}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{job=\"kube_node\", cluster=~\"$cluster\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=\"kube_node\",mode=\"idle\", cluster=~\"$cluster\"}[$__rate_interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"kube_node\", cluster=~\"$cluster\"} / (node_memory_MemTotal_bytes{job=\"kube_node\", cluster=~\"$cluster\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=\"kube_node\",fstype=~\"ext.?|xfs\", cluster=~\"$cluster\"}-node_filesystem_free_bytes{job=\"kube_node\",fstype=~\"ext.?|xfs\", cluster=~\"$cluster\"}) *100/(node_filesystem_avail_bytes {job=\"kube_node\",fstype=~\"ext.?|xfs\", cluster=~\"$cluster\"}+(node_filesystem_size_bytes{job=\"kube_node\",fstype=~\"ext.?|xfs\", cluster=~\"$cluster\"}-node_filesystem_free_bytes{job=\"kube_node\",fstype=~\"ext.?|xfs\", cluster=~\"$cluster\"})))by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=\"kube_node\", cluster=~\"$cluster\"}[$__rate_interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=\"kube_node\", cluster=~\"$cluster\"}[$__rate_interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=\"kube_node\", cluster=~\"$cluster\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=\"kube_node\", cluster=~\"$cluster\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "上传带宽"
    },
    {
     "expr": "((1-(1 - avg(rate(node_cpu_seconds_total{job=\"kube_node\",mode=\"idle\", cluster=~\"$cluster\"}[$__rate_interval])) by (instance))^1.3)^(1/3)*0.5 + \r\n(1-(1 - avg(node_memory_MemAvailable_bytes{job=\"kube_node\", cluster=~\"$cluster\"} / node_memory_MemTotal_bytes{job=\"kube_node\", cluster=~\"$cluster\"})by (instance))^6)^(1/3)*0.3 + \r\n(1 - max(rate(node_disk_io_time_seconds_total{job=\"kube_node\", cluster=~\"$cluster\"}[$__rate_interval]))by (instance)^1.1)^(1/2)*0.2)*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_disk_io_time_seconds_total{job=\"kube_node\", cluster=~\"$cluster\"}[$__rate_interval])) by (instance) *100",
     "legendFormat": "IOutil使用率"
    },
    {
     "expr": "max (node_filesystem_size_bytes{job=\"kube_node\",mountpoint=\"/\",fstype!=\"rootfs\", cluster=~\"$cluster\"}) by (instance)",
     "legendFormat": "Disk size"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"kube_node\", cluster=~\"$cluster\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=\"kube_node\", cluster=~\"$cluster\"} / (node_memory_SwapTotal_bytes{job=\"kube_node\", cluster=~\"$cluster\"})))* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Stability Overview",
   "type": "bargauge",
   "description": "This panel displays the total number of container restarts per pod and container within each namespace, correlated with the reason for the last termination event. ",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(kube_pod_container_status_restarts_total{namespace!~\"kube-system|metallb-system\", cluster=~\"$cluster\"}) by (pod, namespace)\n* on(pod, namespace) group_right()\nsum(kube_pod_container_status_last_terminated_reason{namespace!~\"kube-system|metallb-system\", cluster=~\"$cluster\"}) by (pod, namespace, reason)\nor sum(kube_pod_container_status_restarts_total{namespace!~\"kube-system|metallb-system\", cluster=~\"$cluster\"}) by (pod, namespace)\n* on(pod, namespace) group_right()\nsum(kube_pod_container_status_waiting_reason{namespace!~\"kube-system|metallb-system\", cluster=~\"$cluster\"}) by (pod, namespace, reason)\n) > 0"
    }
   ]
  },
  {
   "title": "Normal Event Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(source) (\n  count_over_time(\n    {source=\"fluent_bit\", job=\"kube_events\", cluster=~\"$cluster\"} \n    | json\n    | type=\"Normal\" \n    [$__range]\n  ) > 0\n)"
    }
   ]
  },
  {
   "title": "Cluster Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{source=\"fluent_bit\", job=\"kube_events\", cluster=~\"$cluster\"} \r\n  | json  \r\n  | line_format `{{if eq .type \"Normal\"}}✅{{else}}⚠️{{end}} | 📦 Object: {{.involvedObject_kind}}/{{.involvedObject_name}} ({{.involvedObject_namespace}}) -> {{.reason}} | 🛠️ Source: {{.source_component}} {{if ne .source_host \"\"}}🌐 Host: {{.source_host}} {{end}}\r\n📝 Message: {{.message | trim}}`"
    }
   ]
  },
  {
   "title": "Warning Event Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(source) (count_over_time({source=\"fluent_bit\", job=\"kube_events\", cluster=~\"$cluster\"} | json | type = `Warning` [$__range])>0)"
    }
   ]
  },
  {
   "title": "Memory usage by namespace",
   "type": "bargauge",
   "description": "The memory usage in a cluster grouped by Kubernetes namespace",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (container_memory_working_set_bytes{pod!=\"\",container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory usage by deployment",
   "type": "bargauge",
   "description": "The memory usage in a cluster grouped by Kubernetes deployment",
   "gridPos": { "h": 13, "w": 9, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (container, namespace) (container_memory_working_set_bytes{container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}))",
     "legendFormat": "{{ namespace }} - {{ container}}"
    }
   ]
  },
  {
   "title": "Memory usage by pod",
   "type": "bargauge",
   "description": "The memory usage in a cluster grouped by Kubernetes pod",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (pod, namespace) (container_memory_working_set_bytes{pod!=\"\",container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}))",
     "legendFormat": "{{ namespace }} - {{ pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage by namespace",
   "type": "bargauge",
   "description": "The CPU usage in a cluster grouped by Kubernetes namespace",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\", cluster=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage by deployment",
   "type": "bargauge",
   "description": "The CPU usage in a cluster grouped by Kubernetes deployment",
   "gridPos": { "h": 13, "w": 9, "x": 7, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (container, namespace) (rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\", cluster=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "{{ namespace }} - {{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage by pod",
   "type": "bargauge",
   "description": "The CPU usage in a cluster grouped by Kubernetes pod",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (pod, namespace) (rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\", cluster=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "{{ namespace }} - {{ pod}}"
    }
   ]
  }
 ]
}