{
 "title": "Kubernetes: Detailed Dashboard",
 "tags": [
  "kubernetes",
  "loki",
  "prometheus",
  "metrics",
  "logs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "loki-ds", "query": "loki" },
   { "name": "prometheus_ds", "label": "prom-ds", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube_node\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$namespace\"},container)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$namespace\", container=~\"$container\"},pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Pod Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}[5m])) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container !=\"\",container!=\"POD\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(sum(rate(container_network_receive_bytes_total{cluster=~\"$cluster\",pod=~\"$pod\",namespace=~\"$namespace\"}[5m])) by (pod)* on(pod) group_right kube_pod_container_info{cluster=~\"$cluster\",pod=~\"$pod\",namespace=~\"$namespace\",container =~\"$container\"}) by(pod) *8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",pod=~\"$pod\",namespace=~\"$namespace\"}[5m])) by (pod)* on(pod) group_right kube_pod_container_info{cluster=~\"$cluster\",pod=~\"$pod\",namespace=~\"$namespace\",container =~\"$container\"}) by(pod) *8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{cluster=~\"$cluster\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}[5m])) by (container,pod,node,namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{cluster=~\"$cluster\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}[5m])) by (container,pod,node,namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - \n  kube_pod_created{cluster=~\"$cluster\",pod=~\"$pod\", namespace=~\"$namespace\"} \n  * on (pod, namespace) group_right(container) \n  kube_pod_container_info{cluster=~\"$cluster\",\n    pod=~\"$pod\", \n    namespace=~\"$namespace\", \n    container=~\"$container\"\n  }",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{cluster=~\"$cluster\",\n  pod=~\"$pod\", \n  container=~\"$container\", \n  container!=\"\", \n  container!=\"POD\", \n  namespace=~\"$namespace\"\n} \n* on (pod, namespace) group_left(node) \nkube_pod_info{cluster=~\"$cluster\",\n  pod=~\"$pod\", \n  namespace=~\"$namespace\"\n}"
    }
   ]
  },
  {
   "title": "Normal Event Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(source) (\n  count_over_time(\n    {source=\"fluent_bit\", job=\"kube_events\", cluster=~\"$cluster\"} \n    | json\n    | type=\"Normal\"\n    | metadata_namespace=~\"$namespace\"\n    [$__range]\n  ) > 0\n)"
    }
   ]
  },
  {
   "title": "Event Volume by  Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (type) (count_over_time(\n  {source=\"fluent_bit\", job=\"kube_events\", cluster=~\"$cluster\"}\n  | json\n  | metadata_namespace=~`$namespace` \n[5m]\n))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cluster Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{source=\"fluent_bit\", job=\"kube_events\", cluster=~\"$cluster\"} \n  | json  \n  | metadata_namespace=~`$namespace` \n  | line_format `{{if eq .type \"Normal\"}}✅{{else}}⚠️{{end}} {{.type}} | 📦 Object: {{.involvedObject_kind}}/{{.involvedObject_name}} ({{.involvedObject_namespace}}) -> {{.reason}} \n🛠️ Source: {{.source_component}} {{if ne .source_host \"\"}}🌐 Host: {{.source_host}} {{end}}\n📝 Message: {{.message | trim}}`"
    }
   ]
  },
  {
   "title": "Warning Event Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(source) (count_over_time({source=\"fluent_bit\", job=\"kube_events\", cluster=~\"$cluster\"}\r\n | json\r\n | metadata_namespace=~\"$namespace\"\r\n | type = `Warning`\r\n  [$__range])>0)"
    }
   ]
  },
  {
   "title": "Logs by Namespace",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (kubernetes_namespace_name) (count_over_time(\n  {source=\"fluent_bit\", job=\"kube_logs\", cluster=~\"$cluster\"}\n  | json\n  | __error__=\"\"\n[$__range]\n))",
     "legendFormat": "{{kubernetes_namespace_name}}"
    }
   ]
  },
  {
   "title": "Logs by Level",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\r\n  count_over_time(\r\n    {source=\"fluent_bit\", job=\"kube_logs\", cluster=~\"$cluster\", kubernetes_namespace_name=~\"$namespace\", kubernetes_container_name=~\"$container\", kubernetes_pod_name=~\"$pod\"} \r\n      | json \r\n      | __error__=\"\"\r\n      | detected_level = \"info\" [$__range]\r\n  )\r\n)",
     "legendFormat": "Info"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\r\n  count_over_time(\r\n    {source=\"fluent_bit\", job=\"kube_logs\", cluster=~\"$cluster\", kubernetes_namespace_name=~\"$namespace\", kubernetes_container_name=~\"$container\", kubernetes_pod_name=~\"$pod\"} \r\n      | json \r\n      | __error__=\"\"\r\n      | detected_level = \"unknown\" [$__range]\r\n  )\r\n)",
     "legendFormat": "Unknown"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\n  count_over_time(\n    {source=\"fluent_bit\", job=\"kube_logs\", cluster=~\"$cluster\", kubernetes_namespace_name=~\"$namespace\", kubernetes_container_name=~\"$container\", kubernetes_pod_name=~\"$pod\"} \n      | json \n      | __error__=\"\"\n      | detected_level = \"warn\" [$__range]\n  )\n)",
     "legendFormat": "Warn"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\r\n  count_over_time(\r\n    {source=\"fluent_bit\", job=\"kube_logs\", cluster=~\"$cluster\", kubernetes_namespace_name=~\"$namespace\", kubernetes_container_name=~\"$container\", kubernetes_pod_name=~\"$pod\"} \r\n      | json \r\n      | __error__=\"\"\r\n      | detected_level = \"error\" [$__range]\r\n  )\r\n)",
     "legendFormat": "Error"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\r\n  count_over_time(\r\n    {source=\"fluent_bit\", job=\"kube_logs\", cluster=~\"$cluster\", kubernetes_namespace_name=~\"$namespace\", kubernetes_container_name=~\"$container\", kubernetes_pod_name=~\"$pod\"} \r\n      | json \r\n      | __error__=\"\"\r\n      | detected_level = \"debug\" [$__range]\r\n  )\r\n)",
     "legendFormat": "Debug"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\r\n  count_over_time(\r\n    {source=\"fluent_bit\", job=\"kube_logs\", cluster=~\"$cluster\", kubernetes_namespace_name=~\"$namespace\", kubernetes_container_name=~\"$container\", kubernetes_pod_name=~\"$pod\"} \r\n      | json \r\n      | __error__=\"\"\r\n      | detected_level = \"critical\" [$__range]\r\n  )\r\n)",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Log Volume by Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (count_over_time(\n  {source=\"fluent_bit\", job=\"kube_logs\", cluster=~\"$cluster\", kubernetes_namespace_name=~\"$namespace\", kubernetes_container_name=~\"$container\", kubernetes_pod_name=~\"$pod\"}\n  | json\n  | detected_level != \"\"\n[5m]\n))",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Recent Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{source=\"fluent_bit\", job=\"kube_logs\", cluster=~\"$cluster\", kubernetes_namespace_name=~\"$namespace\", kubernetes_container_name=~\"$container\", kubernetes_pod_name=~\"$pod\" }\n  | json\n  | regexp `\\[(?P<level>[A-Z]+)\\]`\n  | line_format \"{{.kubernetes_pod_name}} ➡️ {{.log}}\""
    }
   ]
  }
 ]
}