apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-env
  namespace: tools
data:
  AUTHENTIK_POSTGRESQL__HOST: "postgres"
  AUTHENTIK_REDIS__HOST: "valkey"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-server
  namespace: tools
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: authentik-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: authentik-server
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: authentik-server
          image: reg.ygnv.my.id/ghcr/goauthentik/server:2025.10.3
          imagePullPolicy: IfNotPresent
          args: ["server"]
          envFrom:
            - configMapRef:
                name: authentik-env
            - secretRef:
                name: authentik-cred
          resources:
            requests:
              memory: 512Mi
          volumeMounts:
            - mountPath: /media
              name: media-storage
            - mountPath: /certs
              name: certs-storage
            - mountPath: /templates
              name: templates-storage
      volumes:
        - name: media-storage
          hostPath:
            path: /mnt/cephfs/docker/tools/authentik/media
            type: Directory
        - name: certs-storage
          hostPath:
            path: /mnt/cephfs/docker/tools/authentik/certs
            type: Directory
        - name: templates-storage
          hostPath:
            path: /mnt/cephfs/docker/tools/authentik/templates
            type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: tools
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: authentik-worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: authentik-worker
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: authentik-worker
          image: reg.ygnv.my.id/ghcr/goauthentik/server:2025.10.3
          imagePullPolicy: IfNotPresent
          args: ["worker"]
          envFrom:
            - configMapRef:
                name: authentik-env
            - secretRef:
                name: authentik-cred
          resources:
            requests:
              memory: 512Mi
          volumeMounts:
            - mountPath: /media
              name: media-storage
            - mountPath: /certs
              name: certs-storage
            - mountPath: /templates
              name: templates-storage
      volumes:
        - name: media-storage
          hostPath:
            path: /mnt/cephfs/docker/tools/authentik/media
            type: Directory
        - name: certs-storage
          hostPath:
            path: /mnt/cephfs/docker/tools/authentik/certs
            type: Directory
        - name: templates-storage
          hostPath:
            path: /mnt/cephfs/docker/tools/authentik/templates
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-server
  namespace: tools
spec:
  selector:
    app: authentik-server
  ports:
    - protocol: TCP
      name: http
      port: 9000
      targetPort: 9000
    - protocol: TCP
      name: metrics
      port: 9300
      targetPort: 9300
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: tools
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`auth.ygnv.my.id`)
      kind: Rule
      services:
        - name: authentik-server
          port: 9000
  tls:
    certResolver: cloudflare
