# CHANGEDETECTION
apiVersion: apps/v1
kind: Deployment
metadata:
  name: changedetection
  namespace: tools
  labels:
    app: changedetection
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: changedetection
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: changedetection
    spec:
      containers:
      - name: changedetection
        image: reg.ygnv.my.id/docker/linuxserver/changedetection.io:0.50.10
        imagePullPolicy: Always
        resources:
          requests:
            memory: 128Mi
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Asia/Jakarta"
        - name: BASE_URL
          value: ""
        - name: PLAYWRIGHT_DRIVER_URL
          value: ""
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        hostPath:
          path: /mnt/cephfs/docker/tools/changedetection
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: changedetection
  namespace: tools
spec:
  selector:
    app: changedetection
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: changedetection
  namespace: tools
  labels:
    app: changedetection
spec:
  entryPoints:
    - http
    - https
  routes:
  - match: Host(`changedetection.ygnv.my.id`)
    kind: Rule
    services:
    - name: changedetection
      port: 5000
  tls:
    certResolver: cloudflare