---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: esphome-cred
  namespace: tools
spec:
  encryptedData:
    PASSWORD: AgBkdxRRfaNV+ZHDO/DOAHVL5BYIy97OE3m0+rFbcJAr5/qQ0VOd7FEl6fLX8QF0pufUNG+hmfSXL7Cem+Stw6VA/Bbw+A3Z+D+38QU7pyByO6J6i8hC5yrlR9aEvJ8e2MUXL26v+d1FXlo5ju5zQGBoUnYpV/mHIL80+T1tjgz8+h6K36QOZMizTFgXCHEVZa5XOm8RrRmN8N2n1XkFnBxhP2vrgAGItMCwGiT6vXYz49jkx9K4KtafrTX9CGW3jtrBTl6Kwy60kZvCs+unfeLzBE6k2ilhxrjAArVWoEivcevfgM3vqcMVla/MX5ogmjFoeh8XVyWcU/GBYVaVbregB0T6YwJxuWHYhoCVTpfoFzauijGlYe1ArtzyY2zDe89+eo9mvNjLOythpL8PXRegjRnYbkSGpUVGUg21lmX5O4Moi498VSJIFI3dvMVpkwZmqU38VanH2xY0x39yeYPM3lzxvABsKhfwG30EBcvYjl05mQj2aTqV/W+Iw+qsJGXPD85Re/IdpI9FwzLKl7xkipOMKhKLgQ7JMAWB58gwFAbJVpFkchRScsxS97oPpAKlMSyvd6Ffdsnx2REGizw4/aG2t+nO9+X18iZcAHvNYe5ZYvyN+sPJr8s2f/Bj6v0/Hc8WTH8B02HV21tnf2p1Zs3CwqJC3bPiPehuiczyZBm7Yz2T5FLMejovKGqr0/D9ats+1P/GweY=
    USERNAME: AgBQwBC644yog/6AZ2DoESB1bHqeO+Uyq2fIIHm4KOaji7Iw/WRN6DEiZRKYrk4gjo1L3o18DpjxDotdwkfQGa+7S3hUZIQEZdaxqC4U4rzsy7ajaiQH5s6yQY489tTU1MMWsKlomOv1EX73yenNFtn9FYXaQyKrivjGmRptx78TwO5G9m2coV2PqHcaZf4ZU2m1VH4IcMnDNII/pIT8zfd6nLP1EA7Olfj5QlJc7wZNkKEGil+O68VcQsiOyPHKM4HsRBVhThPqLjJaONeGRC46Qp2Pz3zfFIw14O9i08UT81NpwU2VaQ/KT/yepb+9lkPdh1TTesnuwinHFIZb96IMz8fYEYQlXvHq0tEHETC1JWFinXpesSpc2DisWp1qaag16ZSVx9zyq4jRiVeYfFHSB4G9qVQY/6OxOchnnUZ0/cR86BgBkrm2u2yYd5svgqURg8cbA7BOO4MZK2+45yZf7raUnBpw+4KEDF0/H352gaNeGOVEPqXztGRuMwqeBDOPnNjwxk6RgA5FxeKosnldkHyr69J3g65XghD1Ebeh1Jv8ju2A0h2S3Fc1/dEpjJAYQErMZ7f/57ibrQAe63Ca4L4ZEOYvA1Mg6374tvuB3sDa8GHf7TFVnKj5OwSkcvVgJDnNbEmm2soxxrEEJ2gjlIW9g7+6mCXJEbUWlgUntbrzw88n2LsnkQompn6W5+Amt85N
  template:
    metadata:
      creationTimestamp: null
      name: esphome-cred
      namespace: tools
