apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw
  namespace: tools
  labels:
    app: excalidraw
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: excalidraw
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: excalidraw
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: excalidraw
        image: excalidraw/excalidraw:latest@sha256:5d7c8281fba2f688bba5385ea906d78726289a9529a0cdcf2b68cc9515d2c6e3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw
  namespace: tools
spec:
  type: LoadBalancer
  externalIPs:
    - 10.1.1.10
  selector:
    app: excalidraw
  ports:
  - port: 8090
    targetPort: 80