apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: tools
  labels:
    app: homeassistant
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: homeassistant
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: homeassistant
        image: lscr.io/linuxserver/homeassistant:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
        ports:
        - containerPort: 8123
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Asia/Jakarta"
        volumeMounts:
        - name: homeassistant-data
          mountPath: /config
      volumes:
      - name: homeassistant-data
        hostPath:
          path: /mnt/cephfs/docker/tools/homeassistant
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: tools
spec:
  type: LoadBalancer
  externalIPs:
  - 10.1.1.10
  selector:
    app: homeassistant
  ports:
  - port: 8123
    targetPort: 8123

---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: esphome
#   namespace: tools
#   labels:
#     app: esphome
# spec:
#   replicas: 1
#   revisionHistoryLimit: 3
#   selector:
#     matchLabels:
#       app: esphome
#   strategy:
#     type: RollingUpdate
#   template:
#     metadata:
#       labels:
#         app: esphome
#     spec:
#       hostNetwork: true
#       dnsPolicy: ClusterFirstWithHostNet
#       containers:
#       - name: esphome
#         image: ghcr.io/esphome/esphome:latest
#         imagePullPolicy: Always
#         resources:
#           requests:
#             memory: 256Mi
#         ports:
#         - containerPort: 6052
#         env:
#           - name: TZ
#             value: Asia/Jakarta
#         volumeMounts:
#         - name: esphome-data
#           mountPath: /config
#       volumes:
#       - name: esphome-data
#         hostPath:
#           path: /mnt/cephfs/docker/tools/esphome
#           type: Directory
---