apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: tools
  labels:
    app: homeassistant
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: homeassistant
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: homeassistant
        image: lscr.io/linuxserver/homeassistant:2025.4.3
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
        ports:
        - containerPort: 8123
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Asia/Jakarta"
        volumeMounts:
        - name: homeassistant-data
          mountPath: /config
      volumes:
      - name: homeassistant-data
        hostPath:
          path: /mnt/cephfs/docker/tools/homeassistant
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: tools
spec:
  selector:
    app: homeassistant
  ports:
  - port: 8123
    targetPort: 8123
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
  namespace: tools
  labels:
    app: homeassistant
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`homeassistant.ygnv.my.id`)
      kind: Rule
      services:
        - name: homeassistant
          port: 8123
  tls:
    certResolver: cloudflare
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
  namespace: tools
  labels:
    app: esphome
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: esphome
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: esphome
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: esphome
        image: ghcr.io/esphome/esphome:2025.4.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: 128Mi
        ports:
        - containerPort: 6052
        envFrom:
        - secretRef:
            name: esphome-cred
        volumeMounts:
        - name: esphome-data
          mountPath: /config
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: esphome-data
        hostPath:
          path: /mnt/cephfs/docker/tools/esphome
          type: Directory
      - name: localtime
        hostPath:
          path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: esphome
  namespace: tools
spec:
  selector:
    app: esphome
  ports:
  - port: 6052
    targetPort: 6052
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: esphome
  namespace: tools
  labels:
    app: esphome
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`esphome.ygnv.my.id`)
      kind: Rule
      services:
        - name: esphome
          port: 6052
  tls:
    certResolver: cloudflare