apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: tools
  labels:
    app: it-tools
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll 
    keel.sh/match-tag: "true"
    keel.sh/pollSchedule: "@every 6h"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: it-tools
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      containers:
      - name: it-tools
        image: corentinth/it-tools:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 64Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: it-tools
  namespace: tools
spec:
  selector:
    app: it-tools
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: it-tools
  namespace: tools
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`tools.ygnv.my.id`)
      kind: Rule
      services:
        - name: it-tools
          port: 80
  tls:
    certResolver: cloudflare