apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexterm
  namespace: tools
  labels:
    app: nexterm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nexterm
  template:
    metadata:
      labels:
        app: nexterm
    spec:
      containers:
      - name: nexterm
        image: germannewsmaker/nexterm:1.0.3-OPEN-PREVIEW
        imagePullPolicy: Always
        resources:
          requests:
            memory: 128Mi
        ports:
        - containerPort: 6989
        envFrom:
        - secretRef:
            name: nexterm-cred
        volumeMounts:
        - name: nexterm-data
          mountPath: /app/data
      volumes:
      - name: nexterm-data
        hostPath:
          path: /mnt/cephfs/docker/tools/nexterm
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: nexterm
  namespace: tools
spec:
  selector:
    app: nexterm
  ports:
  - protocol: TCP
    port: 6989
    targetPort: 6989
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nexterm
  namespace: tools
  labels:
    app: nexterm
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`nexterm.ygnv.my.id`)
      kind: Rule
      services:
        - name: nexterm
          port: 6989
  tls:
    certResolver: cloudflare
