apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: tools
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:5.2.2
        imagePullPolicy: Always
        env:
        - name: PMA_HOST
          value: "mariadb"
        - name: PMA_PORT
          value: "3306"
        - name: UPLOAD_LIMIT
          value: "1G"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: tools
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  externalIPs:
    - 10.1.1.10
  ports:
  - port: 888
    targetPort: 80