apiVersion: v1
kind: ConfigMap
metadata:
  name: semaphore-env
  namespace: tools
data:
  SEMAPHORE_PORT: ":3000"
  SEMAPHORE_DB_DIALECT: "bolt"
  TZ: "Asia/Jakarta"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore
  namespace: tools
  labels:
    app: semaphore
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: semaphore
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: semaphore
    spec:
      containers:
      - name: semaphore
        image: semaphoreui/semaphore:v2.13.13
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: semaphore-env
        - secretRef:
            name: semaphore-cred
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: data
          mountPath: /var/lib/semaphore
        - name: config
          mountPath: /etc/semaphore
      volumes:
      - name: data
        hostPath:
          path: /mnt/cephfs/docker/tools/semaphore/data
          type: Directory
      - name: config
        hostPath:
          path: /mnt/cephfs/docker/tools/semaphore/config
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: semaphore
  namespace: tools
spec:
  type: LoadBalancer
  externalIPs:
    # - 192.168.192.5
    # - 10.0.1.180
    - 10.1.1.10
  selector:
    app: semaphore
  ports:
  - port: 3003
    targetPort: 3000
---