apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  namespace: tools
  labels:
    app: stirling-pdf
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: stirling-pdf
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stirling-pdf
    spec:
      containers:
      - name: stirling-pdf
        image: stirlingtools/stirling-pdf:0.45.6
        imagePullPolicy: Always
        resources:
          requests:
            memory: 384Mi
        env:
        - name: DOCKER_ENABLE_SECURITY
          value: "false"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: pdf-trainingdata
          mountPath: /usr/share/tesseract-ocr/5/tessdata
        - name: pdf-config
          mountPath: /configs
      volumes:
      - name: pdf-trainingdata
        hostPath:
          path: /mnt/cephfs/docker/tools/pdf/trainingdata
          type: Directory
      - name: pdf-config
        hostPath:
          path: /mnt/cephfs/docker/tools/pdf/config
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf
  namespace: tools
spec:
  selector:
    app: stirling-pdf
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: remove-x-forwarded-server
  namespace: tools
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Server: ""
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: stirling-pdf
  namespace: tools
  labels:
    app: stirling-pdf
spec:
  entryPoints:
  - http
  - https
  routes:
  - match: Host(`pdf.ygnv.my.id`)
    kind: Rule
    services:
    - name: stirling-pdf
      port: 8080
    middlewares:
        - name: remove-x-forwarded-server
          namespace: tools
  tls:
    certResolver: cloudflare