apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: tools
  labels:
    app: vaultwarden
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll 
    keel.sh/match-tag: "true"
    keel.sh/pollSchedule: "@every 6h"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vaultwarden
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - name: vaultwarden
        image: vaultwarden/server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: vaultwarden-data
          mountPath: /data
      volumes:
      - name: vaultwarden-data
        hostPath:
          path: /mnt/cephfs/docker/tools/vaultwarden
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: tools
spec:
  type: LoadBalancer
  externalIPs:
    - 10.1.1.250
  selector:
    app: vaultwarden
  ports:
  - port: 8085
    targetPort: 80