apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: tools
  labels:
    app: vaultwarden
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vaultwarden
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - name: vaultwarden
        image: reg.ygnv.my.id/docker/vaultwarden/server:1.34.2-alpine
        imagePullPolicy: Always
        resources:
          requests:
            memory: 32Mi
        ports:
        - containerPort: 80
        env:
        - name: DOMAIN
          value: "https://vaultwarden.ygnv.my.id"
        volumeMounts:
        - name: vaultwarden-data
          mountPath: /data
      volumes:
      - name: vaultwarden-data
        hostPath:
          path: /mnt/cephfs/docker/tools/vaultwarden
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: tools
spec:
  selector:
    app: vaultwarden
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
  namespace: tools
  labels:
    app: vaultwarden
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`vaultwarden.ygnv.my.id`)
      kind: Rule
      services:
        - name: vaultwarden
          port: 80
  tls:
    certResolver: cloudflare