apiVersion: apps/v1
kind: Deployment
metadata:
  name: warrior
  namespace: tools
  labels:
    app: warrior
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
    keel.sh/pollSchedule: "@every 6h"
spec:
  selector:
    matchLabels:
      app: warrior
  strategy:
    type: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: warrior
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - image: atdr.meo.ws/archiveteam/warrior-dockerfile:latest
        imagePullPolicy: IfNotPresent
        name: warrior
        resources: 
          requests:
            memory: 64Mi
        env:
        - name: DOWNLOADER
          value: YGNV
        - name: SELECTED_PROJECT
          value: auto
        - name: HTTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: warrior-cred
              key: HTTP_USERNAME
        - name: HTTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: warrior-cred
              key: HTTP_PASSWORD
        - name: CONCURRENT_ITEMS
          value: "6"
        ports:
        - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: warrior
spec:
  selector:
    app: warrior
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: warrior
  namespace: tools
spec:
  entryPoints:
  - http
  - https
  routes:
  - match: Host(`warrior.ygnv.my.id`)
    kind: Rule
    services:
    - name: warrior
      port: 8001
  tls:
    certResolver: cloudflare