apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bytebase
  namespace: tools
spec:
  # To prevent data races, only request one replica.
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: bytebase
  template:
    metadata:
      labels:
        app: bytebase
    spec:
      containers:
        - name: bytebase
          image: reg.ygnv.my.id/docker/bytebase/bytebase:3.13.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 384Mi
          envFrom:
            - secretRef:
                name: bytebase-cred
          args: ["--port", "8080"]
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 300
            timeoutSeconds: 10
          volumeMounts:
            - name: bytebase-data
              mountPath: /var/opt/bytebase
      volumes:
        - name: bytebase-data
          hostPath:
            path: /mnt/cephfs/docker/tools/bytebase
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: bytebase
  namespace: tools
spec:
  # Optional
  type: ClusterIP
  selector:
    app: bytebase
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bytebase
  namespace: tools
  labels:
    app: bytebase
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`bytebase.ygnv.my.id`)
      kind: Rule
      services:
        - name: bytebase
          port: 80
  tls: {}
