apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: tools
  labels:
    app: pgadmin
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pgadmin
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: pgadmin
        image: reg.ygnv.my.id/docker/dpage/pgadmin4:9.6
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
        envFrom:
        - secretRef:
            name: pgadmin-cred
        ports:
        - containerPort: 80
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
      volumes:
      - name: pgadmin-data
        hostPath:
          path: /mnt/cephfs/docker/tools/pgadmin
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: tools
spec:
  selector:
    app: pgadmin
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin
  namespace: tools
  labels:
    app: pgadmin
spec:
  entryPoints:
    - http
    - https
  routes:
  - match: Host(`pgadmin.ygnv.my.id`)
    kind: Rule
    services:
    - name: pgadmin
      port: 80
  tls:
    certResolver: cloudflare