apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: tools
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/name: homepage
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      enableServiceLinks: true
      initContainers:
        - name: config-processor
          image: reg.ygnv.my.id/docker/alpine:3.23.3
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache gettext;
              # Process all template files in /templates
              cd /templates;
              for file in *; do
                echo "Processing $file";
                envsubst < "$file" > "/processed-config/$file";
              done;
          volumeMounts:
            - name: config-templates # Contains your raw ConfigMap templates
              mountPath: /templates
            - name: processed-config # Stores processed config files
              mountPath: /processed-config
          envFrom:
            - secretRef:
                name: homepage-cred
      containers:
        - name: homepage
          image: reg.ygnv.my.id/ghcr/gethomepage/homepage:v1.9.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 128Mi
          ports:
            - containerPort: 3000
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "*"
          envFrom:
            - secretRef:
                name: homepage-cred
          volumeMounts:
            - name: processed-config # Mount processed config files
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs
            - name: images
              mountPath: /app/public/images
      volumes:
        - name: config-templates # Holds your ConfigMap with templates
          configMap:
            name: homepage # Name of your existing ConfigMap
        - name: processed-config # Temporary storage for processed files
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: images
          hostPath:
            path: /mnt/cephfs/kube//tools/homepage/images
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: tools
  labels:
    app.kubernetes.io/name: homepage
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: homepage
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: tools
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`dash.ygnv.my.id`)
      kind: Rule
      services:
        - name: homepage
          port: 3000
  tls: {}
