---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAdncszCRlnyIUhMRu/tDTOBVEW+X05t6bxwPw8lZseRH3vokR70x+a63oPPCsqokD0bcMWtjls1cBV0XWzWBRVls36ORaQx/TW5Jl6nitub2pDjMNXyHrnhEzzZRSlfpDdSjsdYRyCb3yRjou44TrOP9p6geNxEvXj/YjStEHba63uCalTXCW+lpSYj2xM5jyNrqoNbo6LRMqgNSGlAc/3D7RUGIKfB5BaV09FeBKFMfeEfGrt+2JKEpT2vRJB3ZuJMfABst3WecewviI57w9/GxISPI19s3kjSvhPFGof44zxpoS+nX8hUlE8BMgYvQLJ/NdPds9Yhr5AHkVaZN2aNdKAkF7Pnq6renI1C1jUClZAj2xBsLvTO+M2/HhRovCdUCSLBjnB9SlODrjyQlaHW6KuJixpYC3iHD8jq4cQnL9pEl+FE7nlgEnq2fsE1eTG4vJTVsJAaGcyACYtXWqhkOnpWe0ATwSIa+N5PPF/CEOFlBa+MeXwibzVVOiumEwHRQZig8uDUw4Or7BUzNRBEcoU4MkY+jhZZBIBC9c96eujwFgt+jHFllYW8lZRHVm4sl1k3i3pQEKPJJu5AzexBUGP5TAYIhhOJNlW0oKIRhHAinK0NR2NXqbrzYCTx8c5CIxkjwKk+DPB7QLgWW/U5jcWdhaO7k/juFwL/nd1ZfxmEpeL8mNo12d6+bQhIj4I2xAPZ5AqfrD+fs3DVaPcBLtdvGx4b+7LGVbQGT6QQ0AQ9ORJIbwR
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
